mod cxx_wrapper;

use std::{
    collections::{BTreeMap, BTreeSet},
    env,
    fs::{self, File},
    io::Write,
    path::{Path, PathBuf},
};

use souffle_rs::{RelationBundle, RelationKind, RelationSchema, TypeRef, ValueKind};

use crate::{BuildError, BuildMetadata, ProgramMetadata};
use cxx_wrapper::render_cxx_wrapper;

pub(crate) fn emit_requested_artifacts(
    metadata: &BuildMetadata,
    schemas: &BTreeMap<String, RelationBundle>,
) -> Result<(), BuildError> {
    for program in &metadata.programs {
        if let Some(schema) = schemas.get(&program.program) {
            validate_schema_bundle(&program.program, schema)?;
        }
    }

    if let Some(header_artifact) = &metadata.c_header_artifact {
        write_text_file(header_artifact, &render_c_header())?;
    }
    if let Some(wrapper_artifact) = &metadata.cxx_wrapper_artifact {
        write_text_file(wrapper_artifact, &render_cxx_wrapper(metadata, schemas))?;
    }

    for program in &metadata.programs {
        let Some(schema) = schemas.get(&program.program) else {
            continue;
        };

        if let Some(schema_artifact) = &program.schema_artifact {
            write_schema_artifact(schema_artifact, schema)?;
        }
        if let Some(typed_api_artifact) = &program.typed_api_artifact {
            let typed_api = render_typed_api(program, schema)?;
            write_text_file(typed_api_artifact, &typed_api)?;
        }
    }
    if let Some(module_artifact) = &metadata.typed_api_module_artifact {
        write_text_file(module_artifact, &render_typed_api_module(metadata))?;
    }

    Ok(())
}

pub(crate) fn validate_schema_bundle(
    program: &str,
    schema: &RelationBundle,
) -> Result<(), BuildError> {
    schema
        .validate()
        .map_err(|source| BuildError::SchemaValidation {
            program: program.to_owned(),
            message: source.to_string(),
        })
}

fn write_schema_artifact(path: &Path, schema: &RelationBundle) -> Result<(), BuildError> {
    if let Some(parent) = path.parent() {
        create_dir_all(parent)?;
    }
    let json = serde_json::to_string_pretty(schema).map_err(|source| {
        BuildError::ArtifactSerialization {
            artifact: path.display().to_string(),
            message: source.to_string(),
        }
    })?;
    write_text_file(path, &json)
}

fn write_text_file(path: &Path, contents: &str) -> Result<(), BuildError> {
    if let Some(parent) = path.parent() {
        create_dir_all(parent)?;
    }
    let mut file = File::create(path).map_err(|source| io_error("create file", path, source))?;
    file.write_all(contents.as_bytes())
        .map_err(|source| io_error("write", path, source))?;
    file.write_all(b"\n")
        .map_err(|source| io_error("write", path, source))?;
    Ok(())
}

fn create_dir_all(path: &Path) -> Result<(), BuildError> {
    fs::create_dir_all(path).map_err(|source| io_error("create directory", path, source))
}

fn io_error(operation: &str, path: &Path, source: std::io::Error) -> BuildError {
    BuildError::Io {
        operation: operation.to_owned(),
        path: path.display().to_string(),
        message: source.to_string(),
    }
}

fn render_typed_api(
    program: &ProgramMetadata,
    schema: &RelationBundle,
) -> Result<String, BuildError> {
    let schema_json = serde_json::to_string_pretty(schema).map_err(|source| {
        BuildError::ArtifactSerialization {
            artifact: format!("typed API schema for program `{}`", program.program),
            message: source.to_string(),
        }
    })?;
    let mut output = String::new();
    let mut names = TypedApiNames::new(schema);
    output.push_str("// @generated by souffle-rs-build\n");
    output.push_str("#![allow(dead_code)]\n");
    output.push_str("#![allow(clippy::needless_lifetimes)]\n");
    output.push_str("#![allow(clippy::needless_pass_by_value)]\n");
    output.push('\n');
    output.push_str("use std::convert::TryFrom;\n\n");
    output.push_str(
        "use souffle_rs::{Program, RelationBundle, RelationHandle, RelationId, RelationKind, RelationSchema, Row, SouffleError, Value};\n\n",
    );

    render_composite_types(&mut output, schema, &mut names);
    for relation in schema.iter() {
        render_row_struct(&mut output, relation, &mut names);
        render_relation_handle(&mut output, relation, &mut names);
    }
    render_typed_decode_helpers(&mut output);

    output.push_str(&format!(
        "pub const PROGRAM_NAME: &str = {};\n",
        rust_string_literal(&program.program)
    ));
    output.push_str(&format!(
        "pub const GENERATED_NAMESPACE: &str = {};\n",
        rust_string_literal(&program.generated_namespace)
    ));
    output.push('\n');
    output.push_str("pub fn schema_json() -> &'static str {\n");
    output.push_str(&format!("    {}\n", rust_string_literal(&schema_json)));
    output.push_str("}\n\n");
    output.push_str("pub fn schema_bundle() -> Result<RelationBundle, SouffleError> {\n");
    output.push_str("    RelationBundle::from_json_str(schema_json())\n");
    output.push_str("}\n");
    Ok(output)
}

fn render_typed_api_module(metadata: &BuildMetadata) -> String {
    let mut output = String::new();
    output.push_str("// @generated by souffle-rs-build\n\n");

    for program in metadata
        .programs
        .iter()
        .filter(|program| program.typed_api_artifact.is_some())
    {
        let artifact = program
            .typed_api_artifact
            .as_ref()
            .expect("filtered typed API artifact");
        output.push_str(&format!(
            "#[path = {}]\n",
            rust_string_literal(&absolute_path_string(artifact))
        ));
        output.push_str(&format!(
            "pub mod {};\n\n",
            module_identifier(&program.program)
        ));
    }

    output.push_str("#[allow(dead_code)]\n");
    output.push_str("pub const PROGRAM_MODULES: &[(&str, &str, &str)] = &[\n");
    for program in metadata
        .programs
        .iter()
        .filter(|program| program.typed_api_artifact.is_some())
    {
        output.push_str(&format!(
            "    ({}, {}, {}),\n",
            rust_string_literal(&program.program),
            rust_string_literal(&module_name(&program.program)),
            rust_string_literal(&program.generated_namespace),
        ));
    }
    output.push_str("];\n");
    output
}

fn absolute_path_string(path: &Path) -> String {
    let path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        env::current_dir()
            .unwrap_or_else(|_| PathBuf::from("."))
            .join(path)
    };
    path.display().to_string()
}

#[derive(Debug, Clone)]
struct RelationTypeNames {
    row: String,
    handle: String,
    iterator: Option<String>,
}

#[derive(Debug, Default)]
struct TypedApiNames {
    relation_names: BTreeMap<String, RelationTypeNames>,
    type_names: BTreeMap<String, String>,
    used_type_names: BTreeSet<String>,
}

impl TypedApiNames {
    fn new(schema: &RelationBundle) -> Self {
        let mut names = Self::default();
        for relation in schema.iter() {
            let row = names.allocate_type_name(
                format!("relation:{}:row", relation.name()),
                row_type_name(relation.name()),
            );
            let handle = names.allocate_type_name(
                format!("relation:{}:handle", relation.name()),
                handle_type_name(relation.name()),
            );
            let iterator = relation.is_printable().then(|| {
                names.allocate_type_name(
                    format!("relation:{}:iterator", relation.name()),
                    typed_iterator_type_name(relation.name()),
                )
            });
            names.relation_names.insert(
                relation.name().to_owned(),
                RelationTypeNames {
                    row,
                    handle,
                    iterator,
                },
            );
        }
        names
    }

    fn row_type(&self, relation: &str) -> &str {
        self.relation_names
            .get(relation)
            .expect("relation names allocated")
            .row
            .as_str()
    }

    fn handle_type(&self, relation: &str) -> &str {
        self.relation_names
            .get(relation)
            .expect("relation names allocated")
            .handle
            .as_str()
    }

    fn iterator_type(&self, relation: &str) -> Option<&str> {
        self.relation_names
            .get(relation)
            .expect("relation names allocated")
            .iterator
            .as_deref()
    }

    fn composite_type(&mut self, base: impl Into<String>) -> String {
        let base = base.into();
        self.allocate_type_name(format!("composite:{base}"), base)
    }

    fn allocate_type_name(&mut self, key: String, base: String) -> String {
        if let Some(name) = self.type_names.get(&key) {
            return name.clone();
        }
        let name = unique_identifier(base, &mut self.used_type_names);
        self.type_names.insert(key, name.clone());
        name
    }
}

fn render_row_struct(output: &mut String, relation: &RelationSchema, names: &mut TypedApiNames) {
    let row_type = names.row_type(relation.name()).to_owned();
    let field_names = field_names_for(relation);
    output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    output.push_str(&format!("pub struct {row_type} {{\n"));
    for (index, attribute) in relation.attributes().iter().enumerate() {
        let type_context = type_context_name(
            names,
            attribute_type_name(&row_type, attribute.name(), index),
            attribute.declared_type(),
        );
        output.push_str(&format!(
            "    pub {}: {},\n",
            field_names[index],
            rust_type(names, &type_context, attribute.declared_type())
        ));
    }
    output.push_str("}\n\n");

    output.push_str(&format!("impl From<{row_type}> for Row {{\n"));
    output.push_str(&format!("    fn from(row: {row_type}) -> Self {{\n"));
    output.push_str("        let _ = &row;\n");
    if relation.attributes().is_empty() {
        output.push_str("        Row::new(Vec::new())\n");
    } else {
        output.push_str("        Row::new(vec![\n");
        for (index, attribute) in relation.attributes().iter().enumerate() {
            let type_context = type_context_name(
                names,
                attribute_type_name(&row_type, attribute.name(), index),
                attribute.declared_type(),
            );
            output.push_str(&format!(
                "            {},\n",
                value_expression(
                    names,
                    &format!("row.{}", field_names[index]),
                    attribute.declared_type(),
                    &type_context
                )
            ));
        }
        output.push_str("        ])\n");
    }
    output.push_str("    }\n");
    output.push_str("}\n\n");

    output.push_str(&format!("impl TryFrom<Row> for {row_type} {{\n"));
    output.push_str("    type Error = SouffleError;\n\n");
    output.push_str("    fn try_from(row: Row) -> Result<Self, Self::Error> {\n");
    output.push_str("        let values = row.into_values();\n");
    output.push_str(&format!(
        "        expect_row_arity({}, {}, values.len())?;\n",
        rust_string_literal(relation.name()),
        relation.arity()
    ));
    if !relation.attributes().is_empty() {
        output.push_str("        let mut values = values.into_iter();\n");
    }
    output.push_str("        Ok(Self {\n");
    for (index, attribute) in relation.attributes().iter().enumerate() {
        let type_context = type_context_name(
            names,
            attribute_type_name(&row_type, attribute.name(), index),
            attribute.declared_type(),
        );
        output.push_str(&format!(
            "            {}: {},\n",
            field_names[index],
            typed_decode_expression(
                names,
                relation.name(),
                attribute.name(),
                attribute.declared_type(),
                "values.next().expect(\"arity checked\")",
                &type_context,
            )
        ));
    }
    output.push_str("        })\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_relation_handle(
    output: &mut String,
    relation: &RelationSchema,
    names: &mut TypedApiNames,
) {
    let handle_type = names.handle_type(relation.name()).to_owned();
    let row_type = names.row_type(relation.name()).to_owned();
    let iterator_type = names.iterator_type(relation.name()).map(str::to_owned);
    if let Some(iterator_type) = &iterator_type {
        render_typed_iterator(output, iterator_type, &row_type);
    }

    output.push_str("#[derive(Debug, Clone, Copy)]\n");
    output.push_str(&format!("pub struct {handle_type};\n\n"));
    output.push_str(&format!("impl {handle_type} {{\n"));
    output.push_str(&format!(
        "    pub const NAME: &str = {};\n",
        rust_string_literal(relation.name())
    ));
    output.push_str(&format!(
        "    pub const ARITY: usize = {};\n",
        relation.arity()
    ));
    output.push_str(&format!(
        "    pub const KIND: &str = {};\n",
        rust_string_literal(relation_kind_name(relation.kind()))
    ));
    output.push_str(&format!(
        "    pub const LOADABLE: bool = {};\n",
        relation.is_loadable()
    ));
    output.push_str(&format!(
        "    pub const PRINTABLE: bool = {};\n",
        relation.is_printable()
    ));
    output.push_str(&format!(
        "    pub fn id() -> RelationId {{\n        RelationId::new({})\n    }}\n",
        relation.id().raw()
    ));
    output.push_str(&format!(
        "    pub fn kind() -> RelationKind {{\n        {}\n    }}\n",
        relation_kind_expression(relation.kind())
    ));
    output.push_str(
        "    pub fn handle() -> RelationHandle {\n        RelationHandle::new(Self::id(), Self::NAME, Self::kind(), Self::LOADABLE, Self::PRINTABLE)\n    }\n",
    );
    output.push_str(
        "    pub fn schema<'program, P>(program: &'program P) -> Result<&'program RelationSchema, SouffleError>\n",
    );
    output.push_str("    where\n");
    output.push_str("        P: Program,\n");
    output.push_str("    {\n");
    output.push_str("        program.relation_schema_by_handle(&Self::handle())\n");
    output.push_str("    }\n");

    if relation.is_loadable() {
        output.push_str("    /// Insert one typed row into this loadable relation.\n");
        output.push_str(
            "    ///\n    /// **Performance note:** this calls `Program::insert_row_by_handle`, so the backend's\n",
        );
        output.push_str(
            "    /// per-row insertion costs apply. Prefer backend-specific bulk ingestion paths for\n",
        );
        output.push_str("    /// large inputs when they are available.\n");
        output.push_str(&format!(
            "    pub fn insert<P>(program: &mut P, row: {row_type}) -> Result<(), SouffleError>\n"
        ));
        output.push_str("    where\n");
        output.push_str("        P: Program,\n");
        output.push_str("    {\n");
        output.push_str("        program.insert_row_by_handle(&Self::handle(), row)\n");
        output.push_str("    }\n");
    }

    if relation.is_printable() {
        let iterator_type = iterator_type.expect("printable relation has a typed iterator");

        output.push_str("    /// Iterate this printable relation as dynamic rows.\n");
        output.push_str(
            "    ///\n    /// **Recommended for large relations:** this streams rows instead of materializing\n",
        );
        output.push_str("    /// the complete relation.\n");
        output.push_str(
            "    pub fn iter<'program, P>(program: &'program P) -> Result<souffle_rs::RelationIterator<'program>, SouffleError>\n",
        );
        output.push_str("    where\n");
        output.push_str("        P: Program,\n");
        output.push_str("    {\n");
        output.push_str("        program.iter_relation_by_handle(&Self::handle())\n");
        output.push_str("    }\n");
        output.push_str("    /// Iterate this printable relation as generated typed rows.\n");
        output.push_str(
            "    ///\n    /// **Recommended for large relations:** consume rows with `next_row()` or\n",
        );
        output.push_str("    /// `next_chunk()` instead of calling `read()`.\n");
        output.push_str(&format!(
            "    pub fn iter_typed<'program, P>(program: &'program P) -> Result<{iterator_type}<'program>, SouffleError>\n"
        ));
        output.push_str("    where\n");
        output.push_str("        P: Program,\n");
        output.push_str("    {\n");
        output.push_str(&format!(
            "        Ok({iterator_type} {{ inner: program.iter_relation_by_handle(&Self::handle())? }})\n"
        ));
        output.push_str("    }\n");
        output.push_str("    /// Materialize this printable relation as generated typed rows.\n");
        output.push_str(
            "    ///\n    /// **Performance note:** this collects the whole relation into a `Vec`. Use\n",
        );
        output.push_str(
            "    /// `iter_typed()`, `next_row()`, or `next_chunk()` for large outputs.\n",
        );
        output.push_str(&format!(
            "    pub fn read<P>(program: &P) -> Result<Vec<{row_type}>, SouffleError>\n"
        ));
        output.push_str("    where\n");
        output.push_str("        P: Program,\n");
        output.push_str("    {\n");
        output.push_str("        let mut rows = Self::iter_typed(program)?;\n");
        output.push_str("        let mut output = Vec::new();\n");
        output.push_str("        while let Some(row) = rows.next_row()? {\n");
        output.push_str("            output.push(row);\n");
        output.push_str("        }\n");
        output.push_str("        Ok(output)\n");
        output.push_str("    }\n");
    }

    output.push_str("}\n\n");
}

fn render_typed_iterator(output: &mut String, iterator_type: &str, row_type: &str) {
    output.push_str("/// Streaming typed iterator for one generated relation.\n");
    output.push_str(
        "///\n/// **Recommended for large relations:** use this iterator instead of generated\n",
    );
    output.push_str("/// relation `read()` helpers to avoid whole-relation materialization.\n");
    output.push_str("#[derive(Debug)]\n");
    output.push_str(&format!("pub struct {iterator_type}<'program> {{\n"));
    output.push_str("    inner: souffle_rs::RelationIterator<'program>,\n");
    output.push_str("}\n\n");
    output.push_str(&format!("impl<'program> {iterator_type}<'program> {{\n"));
    output.push_str("    /// Return the next typed row without collecting the whole relation.\n");
    output.push_str(&format!(
        "    pub fn next_row(&mut self) -> Result<Option<{row_type}>, SouffleError> {{\n"
    ));
    output.push_str("        match self.inner.next_row()? {\n");
    output.push_str(&format!(
        "            Some(row) => Ok(Some({row_type}::try_from(row)?)),\n"
    ));
    output.push_str("            None => Ok(None),\n");
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("    /// Return up to `max_rows` typed rows from this iterator.\n");
    output.push_str(
        "    ///\n    /// **Performance note:** each chunk is materialized as a `Vec`; choose a\n",
    );
    output.push_str("    /// chunk size that balances memory use against backend call overhead.\n");
    output.push_str(&format!(
        "    pub fn next_chunk(&mut self, max_rows: usize) -> Result<Vec<{row_type}>, SouffleError> {{\n"
    ));
    output.push_str("        self.inner\n");
    output.push_str("            .next_chunk(max_rows)?\n");
    output.push_str("            .into_iter()\n");
    output.push_str(&format!("            .map({row_type}::try_from)\n"));
    output.push_str("            .collect()\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_composite_types(output: &mut String, schema: &RelationBundle, names: &mut TypedApiNames) {
    let mut rendered = BTreeSet::new();
    for relation in schema.iter() {
        let row_type = names.row_type(relation.name()).to_owned();
        for (index, attribute) in relation.attributes().iter().enumerate() {
            let type_context = type_context_name(
                names,
                attribute_type_name(&row_type, attribute.name(), index),
                attribute.declared_type(),
            );
            render_composite_type(
                output,
                names,
                relation.name(),
                attribute.name(),
                &type_context,
                attribute.declared_type(),
                &mut rendered,
            );
        }
    }
}

fn render_composite_type(
    output: &mut String,
    names: &mut TypedApiNames,
    relation: &str,
    column: &str,
    type_context: &str,
    type_ref: &TypeRef,
    rendered: &mut BTreeSet<String>,
) {
    match type_ref {
        TypeRef::Record(fields) => {
            for (index, field_type) in fields.iter().enumerate() {
                let field_context = type_context_name(
                    names,
                    record_field_type_name(type_context, index),
                    field_type,
                );
                render_composite_type(
                    output,
                    names,
                    relation,
                    &format!("{column}.{index}"),
                    &field_context,
                    field_type,
                    rendered,
                );
            }
            if !rendered.insert(type_context.to_owned()) {
                return;
            }

            output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
            output.push_str(&format!("pub struct {type_context} {{\n"));
            for (index, field_type) in fields.iter().enumerate() {
                let field_context = type_context_name(
                    names,
                    record_field_type_name(type_context, index),
                    field_type,
                );
                output.push_str(&format!(
                    "    pub {}: {},\n",
                    record_field_name(index),
                    rust_type(names, &field_context, field_type)
                ));
            }
            output.push_str("}\n\n");

            output.push_str(&format!("impl From<{type_context}> for Value {{\n"));
            output.push_str(&format!("    fn from(value: {type_context}) -> Self {{\n"));
            output.push_str("        Value::Record(vec![\n");
            for (index, field_type) in fields.iter().enumerate() {
                let field_context = type_context_name(
                    names,
                    record_field_type_name(type_context, index),
                    field_type,
                );
                output.push_str(&format!(
                    "            {},\n",
                    value_expression(
                        names,
                        &format!("value.{}", record_field_name(index)),
                        field_type,
                        &field_context,
                    )
                ));
            }
            output.push_str("        ])\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");

            output.push_str(&format!("impl TryFrom<Value> for {type_context} {{\n"));
            output.push_str("    type Error = SouffleError;\n\n");
            output.push_str("    fn try_from(value: Value) -> Result<Self, Self::Error> {\n");
            output.push_str(&format!(
                "        let fields = decode_record({}, {}, {}, {}, value)?;\n",
                rust_string_literal(relation),
                rust_string_literal(column),
                rust_string_literal(&type_ref.display_name()),
                fields.len()
            ));
            if !fields.is_empty() {
                output.push_str("        let mut fields = fields.into_iter();\n");
            }
            output.push_str("        Ok(Self {\n");
            for (index, field_type) in fields.iter().enumerate() {
                let field_context = type_context_name(
                    names,
                    record_field_type_name(type_context, index),
                    field_type,
                );
                output.push_str(&format!(
                    "            {}: {},\n",
                    record_field_name(index),
                    typed_decode_expression(
                        names,
                        relation,
                        &format!("{column}.{index}"),
                        field_type,
                        "fields.next().expect(\"arity checked\")",
                        &field_context,
                    )
                ));
            }
            output.push_str("        })\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }
        TypeRef::List(element) => {
            let element_context =
                type_context_name(names, list_element_type_name(type_context), element);
            render_composite_type(
                output,
                names,
                relation,
                &format!("{column}[]"),
                &element_context,
                element,
                rendered,
            );
        }
        TypeRef::Adt { variants, .. } => {
            let variant_names = variant_type_names(variants);
            for (variant, fields) in variants {
                let variant_type = variant_names.get(variant).expect("variant names allocated");
                for (index, field_type) in fields.iter().enumerate() {
                    let field_context = type_context_name(
                        names,
                        adt_field_type_name(type_context, variant_type, index),
                        field_type,
                    );
                    render_composite_type(
                        output,
                        names,
                        relation,
                        &format!("{column}.{variant}.{index}"),
                        &field_context,
                        field_type,
                        rendered,
                    );
                }
            }
            if !rendered.insert(type_context.to_owned()) {
                return;
            }

            output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
            output.push_str(&format!("pub enum {type_context} {{\n"));
            for (variant, fields) in variants {
                let variant_type = variant_names.get(variant).expect("variant names allocated");
                output.push_str(&format!("    {variant_type}"));
                if !fields.is_empty() {
                    let field_types = fields
                        .iter()
                        .enumerate()
                        .map(|(index, field_type)| {
                            let field_context = type_context_name(
                                names,
                                adt_field_type_name(type_context, variant_type, index),
                                field_type,
                            );
                            rust_type(names, &field_context, field_type)
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    output.push_str(&format!("({field_types})"));
                }
                output.push_str(",\n");
            }
            output.push_str("}\n\n");

            output.push_str(&format!("impl From<{type_context}> for Value {{\n"));
            output.push_str(&format!("    fn from(value: {type_context}) -> Self {{\n"));
            output.push_str("        match value {\n");
            for (variant, fields) in variants {
                let variant_type = variant_names.get(variant).expect("variant names allocated");
                let pattern = if fields.is_empty() {
                    format!("{type_context}::{variant_type}")
                } else {
                    let field_names = (0..fields.len())
                        .map(record_field_name)
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{type_context}::{variant_type}({field_names})")
                };
                output.push_str(&format!("            {pattern} => Value::Adt {{\n"));
                output.push_str(&format!(
                    "                variant: {}.to_owned(),\n",
                    rust_string_literal(variant)
                ));
                if fields.is_empty() {
                    output.push_str("                fields: Vec::new(),\n");
                } else {
                    output.push_str("                fields: vec![\n");
                    for (index, field_type) in fields.iter().enumerate() {
                        let field_context = type_context_name(
                            names,
                            adt_field_type_name(type_context, variant_type, index),
                            field_type,
                        );
                        output.push_str(&format!(
                            "                    {},\n",
                            value_expression(
                                names,
                                &record_field_name(index),
                                field_type,
                                &field_context,
                            )
                        ));
                    }
                    output.push_str("                ],\n");
                }
                output.push_str("            },\n");
            }
            output.push_str("        }\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");

            output.push_str(&format!("impl TryFrom<Value> for {type_context} {{\n"));
            output.push_str("    type Error = SouffleError;\n\n");
            output.push_str("    fn try_from(value: Value) -> Result<Self, Self::Error> {\n");
            output.push_str("        let value = value.into_untyped();\n");
            output.push_str("        match value {\n");
            output.push_str(
                "            Value::Adt { variant, fields } => match variant.as_str() {\n",
            );
            for (variant, fields) in variants {
                let variant_type = variant_names.get(variant).expect("variant names allocated");
                output.push_str(&format!(
                    "                {} => {{\n",
                    rust_string_literal(variant)
                ));
                output.push_str(&format!(
                    "                    expect_row_arity({}, {}, fields.len())?;\n",
                    rust_string_literal(&format!("{relation}.{column}.{variant}")),
                    fields.len()
                ));
                if !fields.is_empty() {
                    output.push_str("                    let mut fields = fields.into_iter();\n");
                }
                if fields.is_empty() {
                    output.push_str(&format!("                    Ok(Self::{variant_type})\n"));
                } else {
                    let decoded_fields = fields
                        .iter()
                        .enumerate()
                        .map(|(index, field_type)| {
                            let field_context = type_context_name(
                                names,
                                adt_field_type_name(type_context, variant_type, index),
                                field_type,
                            );
                            typed_decode_expression(
                                names,
                                relation,
                                &format!("{column}.{variant}.{index}"),
                                field_type,
                                "fields.next().expect(\"arity checked\")",
                                &field_context,
                            )
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    output.push_str(&format!(
                        "                    Ok(Self::{variant_type}({decoded_fields}))\n"
                    ));
                }
                output.push_str("                }\n");
            }
            output.push_str("                _ => Err(SouffleError::AdtVariantMismatch {\n");
            output.push_str(&format!(
                "                    relation: {}.to_owned(),\n",
                rust_string_literal(relation)
            ));
            output.push_str(&format!(
                "                    column: {}.to_owned(),\n",
                rust_string_literal(column)
            ));
            output.push_str("                    variant,\n");
            output.push_str("                }),\n");
            output.push_str("            },\n");
            output.push_str(&format!(
                "            value => Err(type_mismatch({}, {}, {}, &value)),\n",
                rust_string_literal(relation),
                rust_string_literal(column),
                rust_string_literal(&type_ref.display_name())
            ));
            output.push_str("        }\n");
            output.push_str("    }\n");
            output.push_str("}\n\n");
        }
        TypeRef::Subtype { base, .. } => {
            render_composite_type(
                output,
                names,
                relation,
                column,
                type_context,
                base,
                rendered,
            );
        }
        TypeRef::Declared { runtime, .. } => {
            render_composite_type(
                output,
                names,
                relation,
                column,
                type_context,
                runtime,
                rendered,
            );
        }
        TypeRef::Number
        | TypeRef::Unsigned
        | TypeRef::Float
        | TypeRef::Symbol
        | TypeRef::Nullary
        | TypeRef::Reference { .. }
        | TypeRef::Union { .. } => {}
    }
}

fn rust_type(names: &mut TypedApiNames, type_context: &str, type_ref: &TypeRef) -> String {
    match type_ref {
        TypeRef::Number => "i64".to_owned(),
        TypeRef::Unsigned => "u64".to_owned(),
        TypeRef::Float => "f64".to_owned(),
        TypeRef::Symbol => "String".to_owned(),
        TypeRef::Nullary => "()".to_owned(),
        TypeRef::Subtype { base, .. } => rust_type(names, type_context, base),
        TypeRef::Declared { runtime, .. } => rust_type(names, type_context, runtime),
        TypeRef::Record(_) | TypeRef::Adt { .. } => type_context.to_owned(),
        TypeRef::List(element) => {
            let element_type_context =
                type_context_name(names, list_element_type_name(type_context), element);
            format!("Vec<{}>", rust_type(names, &element_type_context, element))
        }
        TypeRef::Reference { .. } => "Value".to_owned(),
        TypeRef::Union { .. } => "Value".to_owned(),
    }
}

fn value_expression(
    names: &mut TypedApiNames,
    accessor: &str,
    type_ref: &TypeRef,
    type_context: &str,
) -> String {
    match type_ref {
        TypeRef::Number => format!("Value::Number({accessor})"),
        TypeRef::Unsigned => format!("Value::Unsigned({accessor})"),
        TypeRef::Float => format!("Value::Float({accessor})"),
        TypeRef::Symbol => format!("Value::Symbol({accessor})"),
        TypeRef::Nullary => "Value::Nullary".to_owned(),
        TypeRef::Subtype { name, base } => format!(
            "Value::typed({}, {})",
            rust_string_literal(name),
            value_expression(names, accessor, base, type_context)
        ),
        TypeRef::Declared { name, runtime } => format!(
            "Value::typed({}, {})",
            rust_string_literal(name),
            value_expression(names, accessor, runtime, type_context)
        ),
        TypeRef::Record(_) | TypeRef::Adt { .. } => format!("Value::from({accessor})"),
        TypeRef::List(element) => {
            let element_type_context =
                type_context_name(names, list_element_type_name(type_context), element);
            format!(
                "Value::List({accessor}.into_iter().map(|value| {}).collect())",
                value_expression(names, "value", element, &element_type_context)
            )
        }
        TypeRef::Reference { .. } => accessor.to_owned(),
        TypeRef::Union { .. } => accessor.to_owned(),
    }
}

fn typed_decode_expression(
    names: &mut TypedApiNames,
    relation: &str,
    column: &str,
    type_ref: &TypeRef,
    value: &str,
    type_context: &str,
) -> String {
    match type_ref {
        TypeRef::Number => format!(
            "decode_number({}, {}, {value})?",
            rust_string_literal(relation),
            rust_string_literal(column)
        ),
        TypeRef::Unsigned => format!(
            "decode_unsigned({}, {}, {value})?",
            rust_string_literal(relation),
            rust_string_literal(column)
        ),
        TypeRef::Float => format!(
            "decode_float({}, {}, {value})?",
            rust_string_literal(relation),
            rust_string_literal(column)
        ),
        TypeRef::Symbol => format!(
            "decode_symbol({}, {}, {value})?",
            rust_string_literal(relation),
            rust_string_literal(column)
        ),
        TypeRef::Nullary => format!(
            "decode_nullary({}, {}, {value})?",
            rust_string_literal(relation),
            rust_string_literal(column)
        ),
        TypeRef::Subtype { base, .. } | TypeRef::Declared { runtime: base, .. } => {
            typed_decode_expression(names, relation, column, base, value, type_context)
        }
        TypeRef::Record(_) | TypeRef::Adt { .. } => {
            format!("{type_context}::try_from({value})?")
        }
        TypeRef::List(element) => {
            let element_type_context =
                type_context_name(names, list_element_type_name(type_context), element);
            format!(
                "decode_list({}, {}, {}, {value})?.into_iter().map(|value| -> Result<_, SouffleError> {{ Ok({}) }}).collect::<Result<Vec<_>, SouffleError>>()?",
                rust_string_literal(relation),
                rust_string_literal(column),
                rust_string_literal(&type_ref.display_name()),
                typed_decode_expression(
                    names,
                    relation,
                    &format!("{column}[]"),
                    element,
                    "value",
                    &element_type_context,
                )
            )
        }
        TypeRef::Reference { .. } => format!(
            "decode_value({}, {}, {}, &[{}], {value})?",
            rust_string_literal(relation),
            rust_string_literal(column),
            rust_string_literal(&type_ref.display_name()),
            allowed_value_kinds(type_ref)
                .into_iter()
                .map(rust_string_literal)
                .collect::<Vec<_>>()
                .join(", ")
        ),
        TypeRef::Union { .. } => format!(
            "decode_value({}, {}, {}, &[{}], {value})?",
            rust_string_literal(relation),
            rust_string_literal(column),
            rust_string_literal(&type_ref.display_name()),
            allowed_value_kinds(type_ref)
                .into_iter()
                .map(rust_string_literal)
                .collect::<Vec<_>>()
                .join(", ")
        ),
    }
}

fn type_context_name(names: &mut TypedApiNames, base: String, type_ref: &TypeRef) -> String {
    match type_ref {
        TypeRef::Record(_) | TypeRef::Adt { .. } => names.composite_type(base),
        TypeRef::Subtype { base: inner, .. } | TypeRef::Declared { runtime: inner, .. } => {
            type_context_name(names, base, inner)
        }
        _ => base,
    }
}

fn attribute_type_name(row_type: &str, attribute_name: &str, index: usize) -> String {
    let owner = row_type.strip_suffix("Row").unwrap_or(row_type);
    let attribute = pascal_case(attribute_name);
    if attribute == "Relation" {
        format!("{owner}Column{index}")
    } else {
        format!("{owner}{attribute}")
    }
}

fn record_field_type_name(parent_type: &str, index: usize) -> String {
    format!("{parent_type}Field{index}")
}

fn list_element_type_name(parent_type: &str) -> String {
    format!("{parent_type}Element")
}

fn adt_field_type_name(parent_type: &str, variant: &str, index: usize) -> String {
    format!("{parent_type}{variant}Field{index}")
}

fn record_field_name(index: usize) -> String {
    format!("field_{index}")
}

fn variant_type_name(variant: &str) -> String {
    let mut name = pascal_case(variant);
    if rust_keywords().contains(name.as_str()) || name == "Self" {
        name = format!("Variant{name}");
    }
    name
}

fn variant_type_names(variants: &BTreeMap<String, Vec<TypeRef>>) -> BTreeMap<String, String> {
    let mut used = BTreeSet::new();
    variants
        .keys()
        .map(|variant| {
            (
                variant.clone(),
                unique_identifier(variant_type_name(variant), &mut used),
            )
        })
        .collect()
}

fn unique_identifier(base: String, used: &mut BTreeSet<String>) -> String {
    if used.insert(base.clone()) {
        return base;
    }

    for suffix in 2.. {
        let candidate = format!("{base}{suffix}");
        if used.insert(candidate.clone()) {
            return candidate;
        }
    }
    unreachable!("unbounded suffix search always returns")
}

fn allowed_value_kinds(type_ref: &TypeRef) -> Vec<&'static str> {
    let mut kinds = Vec::new();
    collect_allowed_value_kinds(type_ref, &mut kinds);
    kinds.sort_unstable();
    kinds.dedup();
    kinds
}

fn collect_allowed_value_kinds(type_ref: &TypeRef, kinds: &mut Vec<&'static str>) {
    match type_ref {
        TypeRef::Number => kinds.push(ValueKind::Number.into()),
        TypeRef::Unsigned => kinds.push(ValueKind::Unsigned.into()),
        TypeRef::Float => kinds.push(ValueKind::Float.into()),
        TypeRef::Symbol => kinds.push(ValueKind::Symbol.into()),
        TypeRef::Nullary => kinds.push(ValueKind::Nullary.into()),
        TypeRef::Record(_) => kinds.push(ValueKind::Record.into()),
        TypeRef::List(_) => kinds.push(ValueKind::List.into()),
        TypeRef::Adt { .. } => kinds.push(ValueKind::Adt.into()),
        TypeRef::Reference { runtime, .. } => kinds.push(value_kind_name(*runtime)),
        TypeRef::Subtype { base, .. } => collect_allowed_value_kinds(base, kinds),
        TypeRef::Declared { runtime, .. } => collect_allowed_value_kinds(runtime, kinds),
        TypeRef::Union { variants, .. } => {
            for variant in variants {
                collect_allowed_value_kinds(variant, kinds);
            }
        }
    }
}

fn value_kind_name(kind: ValueKind) -> &'static str {
    kind.into()
}

fn row_type_name(relation_name: &str) -> String {
    format!("{}Row", pascal_case(relation_name))
}

fn handle_type_name(relation_name: &str) -> String {
    format!("{}Relation", pascal_case(relation_name))
}

fn typed_iterator_type_name(relation_name: &str) -> String {
    format!("{}TypedRows", pascal_case(relation_name))
}

fn module_name(program_name: &str) -> String {
    program_name.to_owned()
}

fn module_identifier(program_name: &str) -> String {
    let module = module_name(program_name);
    if rust_keywords().contains(module.as_str()) {
        format!("r#{module}")
    } else {
        module
    }
}

fn pascal_case(value: &str) -> String {
    let mut result = String::new();
    let mut uppercase_next = true;
    for ch in value.chars() {
        if ch.is_ascii_alphanumeric() {
            if uppercase_next {
                result.push(ch.to_ascii_uppercase());
                uppercase_next = false;
            } else {
                result.push(ch);
            }
        } else {
            uppercase_next = true;
        }
    }

    if result.is_empty() {
        "Relation".to_owned()
    } else if result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        format!("Relation{result}")
    } else {
        result
    }
}

fn field_name(attribute_name: &str, index: usize) -> String {
    let mut result = String::new();
    for ch in attribute_name.chars() {
        if ch == '_' || ch.is_ascii_alphanumeric() {
            result.push(ch.to_ascii_lowercase());
        } else {
            result.push('_');
        }
    }
    if result.is_empty() || result.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
        result = format!("column_{index}");
    }

    if rust_keywords().contains(result.as_str()) {
        format!("r#{result}")
    } else {
        result
    }
}

fn field_names_for(relation: &RelationSchema) -> Vec<String> {
    let mut used = BTreeSet::new();
    relation
        .attributes()
        .iter()
        .enumerate()
        .map(|(index, attribute)| unique_identifier(field_name(attribute.name(), index), &mut used))
        .collect()
}

fn rust_keywords() -> BTreeSet<&'static str> {
    [
        "as", "async", "await", "break", "const", "continue", "crate", "dyn", "else", "enum",
        "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move",
        "mut", "pub", "ref", "return", "self", "Self", "static", "struct", "super", "trait",
        "true", "type", "unsafe", "use", "where", "while",
    ]
    .into_iter()
    .collect()
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn relation_kind_name(kind: RelationKind) -> &'static str {
    kind.into()
}

fn relation_kind_expression(kind: RelationKind) -> &'static str {
    match kind {
        RelationKind::Input => "RelationKind::Input",
        RelationKind::Output => "RelationKind::Output",
        RelationKind::Intermediate => "RelationKind::Intermediate",
    }
}

fn render_typed_decode_helpers(output: &mut String) {
    output.push_str(
        r#"fn expect_row_arity(relation: &str, expected: usize, actual: usize) -> Result<(), SouffleError> {
    if expected == actual {
        Ok(())
    } else {
        Err(SouffleError::ArityMismatch {
            relation: relation.to_owned(),
            expected,
            actual,
        })
    }
}

fn decode_number(relation: &str, column: &str, value: Value) -> Result<i64, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Number(value) => Ok(value),
        value => Err(type_mismatch(relation, column, "number", &value)),
    }
}

fn decode_unsigned(relation: &str, column: &str, value: Value) -> Result<u64, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Unsigned(value) => Ok(value),
        value => Err(type_mismatch(relation, column, "unsigned", &value)),
    }
}

fn decode_float(relation: &str, column: &str, value: Value) -> Result<f64, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Float(value) => Ok(value),
        value => Err(type_mismatch(relation, column, "float", &value)),
    }
}

fn decode_symbol(relation: &str, column: &str, value: Value) -> Result<String, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Symbol(value) => Ok(value),
        value => Err(type_mismatch(relation, column, "symbol", &value)),
    }
}

fn decode_nullary(relation: &str, column: &str, value: Value) -> Result<(), SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Nullary => Ok(()),
        value => Err(type_mismatch(relation, column, "nullary", &value)),
    }
}

fn decode_record(
    relation: &str,
    column: &str,
    expected: &str,
    expected_len: usize,
    value: Value,
) -> Result<Vec<Value>, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::Record(fields) if fields.len() == expected_len => Ok(fields),
        Value::Record(fields) => Err(SouffleError::ArityMismatch {
            relation: format!("{relation}.{column}"),
            expected: expected_len,
            actual: fields.len(),
        }),
        value => Err(type_mismatch(relation, column, expected, &value)),
    }
}

fn decode_list(
    relation: &str,
    column: &str,
    expected: &str,
    value: Value,
) -> Result<Vec<Value>, SouffleError> {
    let value = value.into_untyped();
    match value {
        Value::List(elements) => Ok(elements),
        value => Err(type_mismatch(relation, column, expected, &value)),
    }
}

fn decode_value(
    relation: &str,
    column: &str,
    expected: &str,
    allowed_kinds: &[&str],
    value: Value,
) -> Result<Value, SouffleError> {
    let actual = value_kind_name(&value);
    if allowed_kinds.contains(&actual) {
        Ok(value)
    } else {
        Err(SouffleError::TypeMismatch {
            relation: relation.to_owned(),
            column: column.to_owned(),
            expected: expected.to_owned(),
            actual: actual.to_owned(),
        })
    }
}

fn type_mismatch(relation: &str, column: &str, expected: &str, value: &Value) -> SouffleError {
    SouffleError::TypeMismatch {
        relation: relation.to_owned(),
        column: column.to_owned(),
        expected: expected.to_owned(),
        actual: value_kind_name(value).to_owned(),
    }
}

fn value_kind_name(value: &Value) -> &'static str {
    value.kind().as_str()
}

"#,
    );
}

fn render_c_header() -> String {
    let abi_version = souffle_rs_sys::SOUFFLE_RS_ABI_VERSION;
    format!(
        r#"// @generated by souffle-rs-build
#ifndef SOUFFLE_RS_H
#define SOUFFLE_RS_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

#define SOUFFLE_RS_ABI_VERSION {abi_version}u

typedef enum SouffleRsStatus {{
    SOUFFLE_RS_STATUS_OK = 0,
    SOUFFLE_RS_STATUS_ERROR = 1,
    SOUFFLE_RS_STATUS_EXCEPTION = 2,
    SOUFFLE_RS_STATUS_ABI_MISMATCH = 3,
    SOUFFLE_RS_STATUS_NULL_POINTER = 4,
    SOUFFLE_RS_STATUS_CALLBACK_FAILED = 5
}} SouffleRsStatus;

typedef enum SouffleRsValueKind {{
    SOUFFLE_RS_VALUE_NUMBER = 0,
    SOUFFLE_RS_VALUE_UNSIGNED = 1,
    SOUFFLE_RS_VALUE_FLOAT = 2,
    SOUFFLE_RS_VALUE_SYMBOL = 3,
    SOUFFLE_RS_VALUE_RECORD = 4,
    SOUFFLE_RS_VALUE_LIST = 5,
    SOUFFLE_RS_VALUE_ADT = 6,
    SOUFFLE_RS_VALUE_NULLARY = 7
}} SouffleRsValueKind;

typedef struct SouffleRsString {{
    const char* data;
    size_t len;
}} SouffleRsString;

typedef struct SouffleRsCompositeRef {{
    size_t index;
}} SouffleRsCompositeRef;

typedef union SouffleRsValueData {{
    int64_t number;
    uint64_t unsigned_value;
    double float_value;
    SouffleRsString symbol;
    SouffleRsCompositeRef composite;
}} SouffleRsValueData;

typedef struct SouffleRsValue {{
    SouffleRsValueKind kind;
    SouffleRsValueData as;
}} SouffleRsValue;

typedef struct SouffleRsInputComposite {{
    SouffleRsValueKind kind;
    const SouffleRsValue* values;
    size_t len;
    SouffleRsString variant;
}} SouffleRsInputComposite;

typedef struct SouffleRsRow {{
    const char* relation_name;
    const SouffleRsValue* values;
    size_t len;
    const SouffleRsInputComposite* composites;
    size_t composite_count;
}} SouffleRsRow;

typedef struct SouffleRsRunOptions {{
    size_t thread_count;
}} SouffleRsRunOptions;

typedef struct SouffleRsRelationOutput {{
    const char* relation_name;
    const SouffleRsRow* rows;
    size_t len;
    void* owner;
}} SouffleRsRelationOutput;

typedef struct SouffleRsRowOutput {{
    SouffleRsRow row;
    void* owner;
}} SouffleRsRowOutput;

typedef struct SouffleRsError {{
    SouffleRsStatus status;
    SouffleRsString message;
}} SouffleRsError;

typedef struct SouffleRsProgram SouffleRsProgram;
typedef struct SouffleRsRelationIterator SouffleRsRelationIterator;

typedef int (*SouffleRsRowCallback)(
    const SouffleRsRow* row,
    void* user_data
);

uint32_t souffle_rs_abi_version(void);

int souffle_rs_program_new(
    const char* program_name,
    SouffleRsProgram** program_output,
    SouffleRsError* error
);

int souffle_rs_program_set_threads(
    SouffleRsProgram* program,
    size_t thread_count,
    SouffleRsError* error
);

int souffle_rs_program_insert_row(
    SouffleRsProgram* program,
    const SouffleRsRow* row,
    SouffleRsError* error
);

int souffle_rs_program_run(
    SouffleRsProgram* program,
    const SouffleRsRunOptions* options,
    SouffleRsError* error
);

int souffle_rs_program_read_relation(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
);

int souffle_rs_program_open_relation_iterator(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRelationIterator** iterator_output,
    SouffleRsError* error
);

int souffle_rs_relation_iterator_next(
    SouffleRsRelationIterator* iterator,
    uint8_t* has_row_output,
    SouffleRsRowOutput* row_output,
    SouffleRsError* error
);

int souffle_rs_relation_iterator_next_chunk(
    SouffleRsRelationIterator* iterator,
    size_t max_rows,
    uint8_t* has_rows_output,
    SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
);

int souffle_rs_program_for_each_row(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRowCallback callback,
    void* user_data,
    SouffleRsError* error
);

int souffle_rs_relation_output_composite_len(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    size_t* len_output,
    SouffleRsError* error
);

int souffle_rs_relation_output_composite_value(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    size_t index,
    SouffleRsValue* value_output,
    SouffleRsError* error
);

int souffle_rs_relation_output_adt_variant(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    SouffleRsString* variant_output,
    SouffleRsError* error
);

void souffle_rs_program_free(SouffleRsProgram* program);
void souffle_rs_relation_iterator_free(SouffleRsRelationIterator* iterator);
void souffle_rs_row_output_free(SouffleRsRowOutput* row_output);
void souffle_rs_relation_output_free(SouffleRsRelationOutput* relation_output);
void souffle_rs_error_free(SouffleRsError* error);

#ifdef __cplusplus
}}
#endif

#endif
"#
    )
}
