use std::{collections::BTreeMap, path::PathBuf};

use serde::{Deserialize, Serialize};

use crate::{CppStandard, ExternalLibraryKind, GeneratedMode, LinkMode, NativeLinkMode};

/// Machine-readable metadata emitted by the build helper.
///
/// Metadata is the stable handoff between `build.rs`, generated typed APIs,
/// runtime wrappers, CI diagnostics, and downstream tools that need to inspect
/// where generated artifacts were written.
///
/// # Example
///
/// ```
/// use souffle_rs_build::{Build, GeneratedMode};
///
/// let metadata = Build::new()
///     .program("analysis", "logic/main.dl")
///     .generated_mode(GeneratedMode::Directory)
///     .emit_typed_api(true)
///     .metadata()
///     .unwrap();
/// let json = metadata.to_json_pretty().unwrap();
///
/// assert_eq!(metadata.programs[0].program, "analysis");
/// assert!(json.contains("\"abi_version\""));
/// ```
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BuildMetadata {
    /// Path where this JSON metadata document is emitted.
    pub metadata_path: PathBuf,
    /// Build output directory used for generated artifacts.
    pub out_dir: PathBuf,
    /// Generated C ABI header path, when requested.
    pub c_header_artifact: Option<PathBuf>,
    /// Generated C++ wrapper source path, when requested.
    pub cxx_wrapper_artifact: Option<PathBuf>,
    /// Generated Rust module file that re-exports per-program typed APIs.
    pub typed_api_module_artifact: Option<PathBuf>,
    /// All files generated by this build helper invocation.
    pub generated_files: Vec<PathBuf>,
    /// Per-program metadata entries.
    pub programs: Vec<ProgramMetadata>,
    /// Souffle executable used for generation.
    pub souffle_bin: PathBuf,
    /// Souffle include directory used for generated C++ compilation.
    pub souffle_include: Option<PathBuf>,
    /// Souffle version string recorded for reproducibility.
    pub souffle_version: Option<String>,
    /// Souffle include paths passed to generation.
    pub include_dirs: Vec<PathBuf>,
    /// Native library search paths passed to generation and linking.
    pub library_dirs: Vec<PathBuf>,
    /// Macro definitions passed to Souffle generation.
    pub macros: BTreeMap<String, String>,
    /// Generated C++ output mode.
    pub generated_mode: GeneratedMode,
    /// Custom wrapper source path, when one was configured.
    pub wrapper_source: Option<PathBuf>,
    /// Overall native link strategy.
    pub link_mode: LinkMode,
    /// OpenMP configuration recorded for generated C++.
    pub openmp: OpenMpMetadata,
    /// External libraries and functor libraries recorded for linking.
    pub libraries: Vec<ExternalLibraryMetadata>,
    /// Native C++ compilation inputs and outputs.
    pub native: NativeBuildMetadata,
    /// C ABI version expected by generated wrappers and Rust bindings.
    pub abi_version: u32,
}

impl BuildMetadata {
    /// Serialize metadata in a stable, human-readable JSON form.
    pub fn to_json_pretty(&self) -> Result<String, crate::BuildError> {
        serde_json::to_string_pretty(self).map_err(|source| {
            crate::BuildError::MetadataSerialization {
                message: source.to_string(),
            }
        })
    }
}

/// Per-program build metadata.
///
/// Each configured Souffle entrypoint produces one `ProgramMetadata` record
/// describing its generated C++ artifact, optional schema JSON, optional typed
/// Rust API, and generated source files known at metadata time.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProgramMetadata {
    /// Logical program name.
    pub program: String,
    /// Souffle entrypoint `.dl` path.
    pub entrypoint: PathBuf,
    /// C++ namespace used by Souffle generation.
    pub generated_namespace: String,
    /// Primary generated C++ artifact path.
    pub generated_artifact: PathBuf,
    /// Generated schema JSON path, when schema emission was requested.
    pub schema_artifact: Option<PathBuf>,
    /// Generated typed Rust API path, when typed API emission was requested.
    pub typed_api_artifact: Option<PathBuf>,
    /// Generated C++ sources that must be compiled for this program.
    pub generated_sources: Vec<PathBuf>,
}

/// Native C++ compilation and linking inputs for generated Souffle artifacts.
///
/// These fields are useful for reproducing a native compile outside Cargo and
/// for auditing which include paths, defines, libraries, rpaths, and wrapper
/// sources were used for an embedded backend build.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NativeBuildMetadata {
    /// Whether the build helper invoked a native C++ compiler.
    pub compile_enabled: bool,
    /// Static library name produced for generated native code.
    pub static_library: Option<String>,
    /// Target triple used for native compilation.
    pub target_triple: Option<String>,
    /// Native compiler path, when explicitly configured or discovered.
    pub compiler: Option<PathBuf>,
    /// C++ language standard used by generated and wrapper sources.
    pub cpp_standard: CppStandard,
    /// Preprocessor defines passed to native compilation.
    pub defines: Vec<String>,
    /// Compiler flags passed to native compilation.
    pub compile_flags: Vec<String>,
    /// Include directories passed to native compilation.
    pub include_dirs: Vec<PathBuf>,
    /// Library search directories passed to native compilation/linking.
    pub library_dirs: Vec<PathBuf>,
    /// Libraries linked into or alongside generated native artifacts.
    pub link_libraries: Vec<String>,
    /// Runtime search paths emitted for dynamic dependencies.
    pub rpaths: Vec<PathBuf>,
    /// macOS install name, when configured.
    pub install_name: Option<String>,
    /// C++ wrapper source files compiled with generated code.
    pub wrapper_sources: Vec<PathBuf>,
}

/// OpenMP metadata for generated C++.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct OpenMpMetadata {
    /// Whether OpenMP support is enabled for generated code.
    pub enabled: bool,
    /// OpenMP runtime library name, such as `gomp` or `omp`.
    pub runtime: Option<String>,
    /// Static or dynamic OpenMP runtime link mode.
    pub link_mode: NativeLinkMode,
    /// Compiler flags required for OpenMP.
    pub flags: Vec<String>,
}

/// Explicit external library metadata.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ExternalLibraryMetadata {
    /// Linker library name.
    pub name: String,
    /// Semantic role of the library.
    pub kind: ExternalLibraryKind,
    /// Native library search paths.
    pub search_paths: Vec<PathBuf>,
    /// Additional dependent library names.
    pub link_libraries: Vec<String>,
    /// Static or dynamic link mode for this library.
    pub link_mode: NativeLinkMode,
}

/// Backwards-compatible alias for custom-functor metadata entries.
pub type FunctorMetadata = ExternalLibraryMetadata;
