use std::collections::BTreeMap;

use souffle_rs::{RelationBundle, TypeRef};
use strum::IntoStaticStr;

use crate::BuildMetadata;

pub(crate) fn render_cxx_wrapper(
    metadata: &BuildMetadata,
    schemas: &BTreeMap<String, RelationBundle>,
) -> String {
    let abi_version = souffle_rs_sys::SOUFFLE_RS_ABI_VERSION;
    let mut output = String::new();
    output.push_str("// @generated by souffle-rs-build\n");
    output.push_str("#include \"souffle_rs.h\"\n");
    output.push_str("#include \"souffle/SouffleInterface.h\"\n");
    output.push_str("#include <algorithm>\n");
    output.push_str("#include <cstddef>\n");
    output.push_str("#include <cstdint>\n");
    output.push_str("#include <cstring>\n");
    output.push_str("#include <exception>\n");
    output.push_str("#include <memory>\n");
    output.push_str("#include <stdexcept>\n");
    output.push_str("#include <string>\n");
    output.push_str("#include <utility>\n");
    output.push_str("#include <vector>\n\n");

    output.push_str("namespace souffle {\n");
    for program in &metadata.programs {
        output.push_str(&format!(
            "SouffleProgram* newInstance_{}();\n",
            program.program
        ));
    }
    output.push_str("}\n\n");

    output.push_str("struct SouffleRsProgram {\n");
    output.push_str(
        "    SouffleRsProgram(std::string name_arg, souffle::SouffleProgram* program_arg) : name(std::move(name_arg)), program(program_arg) {}\n",
    );
    output.push_str("    std::string name;\n");
    output.push_str("    std::unique_ptr<souffle::SouffleProgram> program;\n");
    output.push_str("};\n\n");

    output.push_str("struct SouffleRsRelationIterator {\n");
    output.push_str(
        "    SouffleRsRelationIterator(SouffleRsProgram* program_arg, souffle::Relation* relation_arg) : program(program_arg), relation(relation_arg), current(relation_arg->begin()), end(relation_arg->end()) {}\n",
    );
    output.push_str("    SouffleRsProgram* program;\n");
    output.push_str("    souffle::Relation* relation;\n");
    output.push_str("    souffle::Relation::iterator current;\n");
    output.push_str("    souffle::Relation::iterator end;\n");
    output.push_str("};\n\n");

    output.push_str(
        r#"namespace {

enum class SchemaTypeKind {
    Number,
    Unsigned,
    Float,
    Symbol,
    Nullary,
    Record,
    List,
    Adt,
    Subtype,
    Union,
    Reference,
    Declared
};

struct SchemaType;

struct SchemaAdtVariant {
    const char* name;
    const SchemaType* fields;
    std::size_t field_count;
};

struct SchemaType {
    SchemaTypeKind kind;
    const char* name;
    const SchemaType* children;
    std::size_t child_count;
    const SchemaType* inner;
    const SchemaAdtVariant* adt_variants;
    std::size_t adt_variant_count;
    bool adt_variants_ordered;
    bool adt_is_enum;
};

struct SchemaAttribute {
    const char* name;
    const SchemaType* type;
};

struct SchemaRelation {
    const char* program;
    const char* relation;
    const SchemaAttribute* attributes;
    std::size_t attribute_count;
};

struct CompositeNode {
    SouffleRsValueKind kind;
    std::vector<SouffleRsValue> values;
    SouffleRsString variant;
};

struct OwnedRelationOutput {
    std::string relation_name;
    std::vector<SouffleRsRow> rows;
    std::vector<std::unique_ptr<SouffleRsValue[]>> row_values;
    std::vector<std::unique_ptr<char[]>> strings;
    std::vector<CompositeNode> composites;
};

int status(SouffleRsStatus status_code) {
    return static_cast<int>(status_code);
}

SouffleRsString null_string() {
    return SouffleRsString{nullptr, 0};
}

SouffleRsString copy_string(OwnedRelationOutput& owner, const std::string& value) {
    if (value.empty()) {
        return null_string();
    }
    auto buffer = std::make_unique<char[]>(value.size());
    std::memcpy(buffer.get(), value.data(), value.size());
    SouffleRsString copied{buffer.get(), value.size()};
    owner.strings.push_back(std::move(buffer));
    return copied;
}

std::string borrowed_string(SouffleRsString value) {
    if (value.len == 0) {
        return std::string();
    }
    if (value.data == nullptr) {
        throw std::invalid_argument("string data is null while len is non-zero");
    }
    return std::string(value.data, value.len);
}

int set_error(SouffleRsError* error, SouffleRsStatus status_code, const std::string& message) {
    if (error != nullptr) {
        souffle_rs_error_free(error);
        error->status = status_code;
        if (message.empty()) {
            error->message = null_string();
        } else {
            auto* data = new char[message.size()];
            std::memcpy(data, message.data(), message.size());
            error->message = SouffleRsString{data, message.size()};
        }
    }
    return status(status_code);
}

template <typename Fn>
int catch_boundary(SouffleRsError* error, Fn&& fn) {
    try {
        return fn();
    } catch (const std::exception& exception) {
        return set_error(error, SOUFFLE_RS_STATUS_EXCEPTION, exception.what());
    } catch (...) {
        return set_error(error, SOUFFLE_RS_STATUS_EXCEPTION, "unknown C++ exception");
    }
}

"#,
    );
    output.push_str(&render_schema_metadata(metadata, schemas));

    output.push_str("souffle::SouffleProgram* create_program_by_name(const std::string& name) {\n");
    for program in &metadata.programs {
        output.push_str(&format!(
            "    if (name == {}) {{\n        return souffle::newInstance_{}();\n    }}\n",
            cxx_string_literal(&program.program),
            program.program
        ));
    }
    output.push_str("    return nullptr;\n");
    output.push_str("}\n\n");

    output.push_str(
        r#"souffle::Relation* relation_by_name(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsError* error
) {
    if (program == nullptr || program->program == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "program");
        return nullptr;
    }
    if (relation_name == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "relation_name");
        return nullptr;
    }
    auto* relation = program->program->getRelation(relation_name);
    if (relation == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_ERROR, std::string("relation not found: ") + relation_name);
        return nullptr;
    }
    return relation;
}

char attr_tag(const souffle::Relation* relation, std::size_t column) {
    const char* attr_type = relation->getAttrType(column);
    if (attr_type == nullptr || attr_type[0] == '\0') {
        return '\0';
    }
    return attr_type[0];
}

std::string attr_type_name(const souffle::Relation* relation, std::size_t column) {
    const char* attr_type = relation->getAttrType(column);
    return attr_type == nullptr ? std::string("<null>") : std::string(attr_type);
}

int type_error(
    SouffleRsError* error,
    const souffle::Relation* relation,
    std::size_t column,
    const std::string& actual
) {
    return set_error(
        error,
        SOUFFLE_RS_STATUS_ERROR,
        "relation `" + relation->getName() + "` column `" + std::to_string(column) +
            "` expects `" + attr_type_name(relation, column) + "` but received `" + actual + "`"
    );
}

const SchemaType* schema_type_for_column(
    const std::string& program_name,
    const std::string& relation_name,
    std::size_t column
);

bool schema_matches_attr_tag(const SchemaType& schema, char tag);

std::string schema_type_name(const SchemaType& schema);

int pack_input_schema_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
);

int append_value(
    SouffleRsProgram* program,
    souffle::tuple& tuple,
    const souffle::Relation* relation,
    std::size_t column,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    SouffleRsError* error
) {
    switch (value.kind) {
    case SOUFFLE_RS_VALUE_NUMBER:
        if (attr_tag(relation, column) != 'i') {
            return type_error(error, relation, column, "number");
        }
        tuple << static_cast<souffle::RamSigned>(value.as.number);
        return status(SOUFFLE_RS_STATUS_OK);
    case SOUFFLE_RS_VALUE_UNSIGNED:
        if (attr_tag(relation, column) != 'u') {
            return type_error(error, relation, column, "unsigned");
        }
        tuple << static_cast<souffle::RamUnsigned>(value.as.unsigned_value);
        return status(SOUFFLE_RS_STATUS_OK);
    case SOUFFLE_RS_VALUE_FLOAT:
        if (attr_tag(relation, column) != 'f') {
            return type_error(error, relation, column, "float");
        }
        tuple << static_cast<souffle::RamFloat>(value.as.float_value);
        return status(SOUFFLE_RS_STATUS_OK);
    case SOUFFLE_RS_VALUE_SYMBOL:
        if (attr_tag(relation, column) != 's') {
            return type_error(error, relation, column, "symbol");
        }
        tuple << borrowed_string(value.as.symbol);
        return status(SOUFFLE_RS_STATUS_OK);
    case SOUFFLE_RS_VALUE_RECORD:
    case SOUFFLE_RS_VALUE_LIST:
    case SOUFFLE_RS_VALUE_ADT: {
        const SchemaType* schema = schema_type_for_column(program->name, relation->getName(), column);
        if (schema == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "schema metadata is required for input composite packing");
        }
        if (!schema_matches_attr_tag(*schema, attr_tag(relation, column))) {
            return type_error(error, relation, column, schema_type_name(*schema));
        }
        souffle::RamDomain packed = 0;
        int pack_status = pack_input_schema_value(program, *schema, row, value, packed, error);
        if (pack_status != status(SOUFFLE_RS_STATUS_OK)) {
            return pack_status;
        }
        tuple << static_cast<souffle::RamSigned>(packed);
        return status(SOUFFLE_RS_STATUS_OK);
    }
    case SOUFFLE_RS_VALUE_NULLARY:
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "nullary value cannot be used as a relation column");
    }
    return set_error(error, SOUFFLE_RS_STATUS_ERROR, "unknown value kind");
}

const SchemaType* schema_type_for_column(
    const std::string& program_name,
    const std::string& relation_name,
    std::size_t column
) {
    for (const SchemaRelation& relation : GENERATED_SCHEMA_RELATIONS) {
        if (relation.program == nullptr || relation.relation == nullptr) {
            continue;
        }
        if (program_name == relation.program && relation_name == relation.relation) {
            if (column >= relation.attribute_count) {
                return nullptr;
            }
            return relation.attributes[column].type;
        }
    }
    return nullptr;
}

bool schema_matches_attr_tag(const SchemaType& schema, char tag) {
    switch (schema.kind) {
    case SchemaTypeKind::Number:
        return tag == 'i';
    case SchemaTypeKind::Unsigned:
        return tag == 'u';
    case SchemaTypeKind::Float:
        return tag == 'f';
    case SchemaTypeKind::Symbol:
        return tag == 's';
    case SchemaTypeKind::Record:
    case SchemaTypeKind::List:
        return tag == 'r';
    case SchemaTypeKind::Adt:
        return tag == '+';
    case SchemaTypeKind::Subtype:
    case SchemaTypeKind::Reference:
    case SchemaTypeKind::Declared:
        return schema.inner != nullptr && schema_matches_attr_tag(*schema.inner, tag);
    case SchemaTypeKind::Union:
        for (std::size_t index = 0; index < schema.child_count; ++index) {
            if (schema_matches_attr_tag(schema.children[index], tag)) {
                return true;
            }
        }
        return false;
    case SchemaTypeKind::Nullary:
        return false;
    }
    return false;
}

std::string schema_type_name(const SchemaType& schema) {
    return schema.name == nullptr ? std::string("<unnamed>") : std::string(schema.name);
}

std::string value_declared_type_name(const SouffleRsValue& value) {
    return borrowed_string(value.declared_type);
}

bool schema_declared_type_matches(const SchemaType& schema, const std::string& declared_type) {
    return !declared_type.empty() && schema.name != nullptr && declared_type == schema.name;
}

std::string input_value_kind_name(SouffleRsValueKind kind) {
    switch (kind) {
    case SOUFFLE_RS_VALUE_NUMBER:
        return "number";
    case SOUFFLE_RS_VALUE_UNSIGNED:
        return "unsigned";
    case SOUFFLE_RS_VALUE_FLOAT:
        return "float";
    case SOUFFLE_RS_VALUE_SYMBOL:
        return "symbol";
    case SOUFFLE_RS_VALUE_RECORD:
        return "record";
    case SOUFFLE_RS_VALUE_LIST:
        return "list";
    case SOUFFLE_RS_VALUE_ADT:
        return "adt";
    case SOUFFLE_RS_VALUE_NULLARY:
        return "nullary";
    }
    return "unknown";
}

bool schema_runtime_tag(const SchemaType& schema, char& tag_output, std::string& error_output) {
    switch (schema.kind) {
    case SchemaTypeKind::Number:
        tag_output = 'i';
        return true;
    case SchemaTypeKind::Unsigned:
        tag_output = 'u';
        return true;
    case SchemaTypeKind::Float:
        tag_output = 'f';
        return true;
    case SchemaTypeKind::Symbol:
        tag_output = 's';
        return true;
    case SchemaTypeKind::Record:
    case SchemaTypeKind::List:
        tag_output = 'r';
        return true;
    case SchemaTypeKind::Adt:
        tag_output = '+';
        return true;
    case SchemaTypeKind::Subtype:
    case SchemaTypeKind::Reference:
    case SchemaTypeKind::Declared:
        if (schema.inner == nullptr) {
            error_output = "schema wrapper type has no runtime type";
            return false;
        }
        return schema_runtime_tag(*schema.inner, tag_output, error_output);
    case SchemaTypeKind::Union: {
        if (schema.child_count == 0 || schema.children == nullptr) {
            error_output = "union schema has no variants";
            return false;
        }
        char expected_tag = 0;
        for (std::size_t index = 0; index < schema.child_count; ++index) {
            char child_tag = 0;
            if (!schema_runtime_tag(schema.children[index], child_tag, error_output)) {
                return false;
            }
            if (index == 0) {
                expected_tag = child_tag;
            } else if (child_tag != expected_tag) {
                error_output = "union schema variants have incompatible runtime tags";
                return false;
            }
        }
        tag_output = expected_tag;
        return true;
    }
    case SchemaTypeKind::Nullary:
        error_output = "nullary type has no relation column runtime tag";
        return false;
    }
    error_output = "unknown schema type kind";
    return false;
}

bool input_value_matches_schema(const SchemaType& schema, const SouffleRsValue& value) {
    switch (schema.kind) {
    case SchemaTypeKind::Number:
        return value.kind == SOUFFLE_RS_VALUE_NUMBER;
    case SchemaTypeKind::Unsigned:
        return value.kind == SOUFFLE_RS_VALUE_UNSIGNED;
    case SchemaTypeKind::Float:
        return value.kind == SOUFFLE_RS_VALUE_FLOAT;
    case SchemaTypeKind::Symbol:
        return value.kind == SOUFFLE_RS_VALUE_SYMBOL;
    case SchemaTypeKind::Nullary:
        return value.kind == SOUFFLE_RS_VALUE_NULLARY;
    case SchemaTypeKind::Record:
        return value.kind == SOUFFLE_RS_VALUE_RECORD;
    case SchemaTypeKind::List:
        return value.kind == SOUFFLE_RS_VALUE_LIST;
    case SchemaTypeKind::Adt:
        return value.kind == SOUFFLE_RS_VALUE_ADT;
    case SchemaTypeKind::Subtype:
    case SchemaTypeKind::Reference:
    case SchemaTypeKind::Declared:
        return schema.inner != nullptr && input_value_matches_schema(*schema.inner, value);
    case SchemaTypeKind::Union:
        for (std::size_t index = 0; index < schema.child_count; ++index) {
            if (input_value_matches_schema(schema.children[index], value)) {
                return true;
            }
        }
        return false;
    }
    return false;
}

const SouffleRsInputComposite* input_composite_for_value(
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    SouffleRsValueKind expected_kind,
    SouffleRsError* error
) {
    const std::size_t index = value.as.composite.index;
    if (index >= row.composite_count) {
        set_error(error, SOUFFLE_RS_STATUS_ERROR, "input composite reference is out of bounds");
        return nullptr;
    }
    if (row.composites == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "row.composites");
        return nullptr;
    }
    const SouffleRsInputComposite& composite = row.composites[index];
    if (composite.kind != expected_kind) {
        set_error(
            error,
            SOUFFLE_RS_STATUS_ERROR,
            "input composite kind mismatch: expected `" + input_value_kind_name(expected_kind) + "` but received `" +
                input_value_kind_name(composite.kind) + "`"
        );
        return nullptr;
    }
    if (composite.len != 0 && composite.values == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "input composite values");
        return nullptr;
    }
    return &composite;
}

int pack_input_schema_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
);

int pack_input_record_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
) {
    const SouffleRsInputComposite* composite =
        input_composite_for_value(row, value, SOUFFLE_RS_VALUE_RECORD, error);
    if (composite == nullptr) {
        return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
    }
    if (schema.child_count != composite->len) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input record field count does not match schema");
    }

    std::vector<souffle::RamDomain> fields;
    fields.resize(schema.child_count);
    for (std::size_t index = 0; index < schema.child_count; ++index) {
        int field_status =
            pack_input_schema_value(program, schema.children[index], row, composite->values[index], fields[index], error);
        if (field_status != status(SOUFFLE_RS_STATUS_OK)) {
            return field_status;
        }
    }
    output = program->program->getRecordTable().pack(fields.data(), fields.size());
    return status(SOUFFLE_RS_STATUS_OK);
}

int pack_input_list_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
) {
    if (schema.child_count != 1 || schema.children == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "list schema must have exactly one element type");
    }
    const SouffleRsInputComposite* composite = input_composite_for_value(row, value, SOUFFLE_RS_VALUE_LIST, error);
    if (composite == nullptr) {
        return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
    }

    souffle::RamDomain tail = 0;
    for (std::size_t offset = 0; offset < composite->len; ++offset) {
        const std::size_t index = composite->len - 1 - offset;
        souffle::RamDomain element = 0;
        int element_status =
            pack_input_schema_value(program, schema.children[0], row, composite->values[index], element, error);
        if (element_status != status(SOUFFLE_RS_STATUS_OK)) {
            return element_status;
        }
        souffle::RamDomain pair[2] = {element, tail};
        tail = program->program->getRecordTable().pack(pair, 2);
    }
    output = tail;
    return status(SOUFFLE_RS_STATUS_OK);
}

int pack_input_adt_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
) {
    const SouffleRsInputComposite* composite = input_composite_for_value(row, value, SOUFFLE_RS_VALUE_ADT, error);
    if (composite == nullptr) {
        return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
    }
    if (schema.adt_variant_count == 0 || schema.adt_variants == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "ADT schema has no variants");
    }
    if (schema.adt_variant_count != 1 && !schema.adt_variants_ordered) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "ordered ADT variant metadata is required before packing multi-variant ADT input");
    }

    const std::string variant_name = borrowed_string(composite->variant);
    const SchemaAdtVariant* variant = nullptr;
    std::size_t variant_index = 0;
    for (std::size_t index = 0; index < schema.adt_variant_count; ++index) {
        const char* candidate = schema.adt_variants[index].name;
        if (candidate != nullptr && variant_name == candidate) {
            variant = &schema.adt_variants[index];
            variant_index = index;
            break;
        }
    }
    if (variant == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input ADT variant is not in schema: " + variant_name);
    }
    if (variant->field_count != composite->len) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input ADT field count does not match schema");
    }
    if (variant->field_count != 0 && variant->fields == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "ADT variant schema has fields but no field metadata");
    }
    if (schema.adt_is_enum) {
        if (variant->field_count != 0) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "enum ADT variant schema unexpectedly has fields");
        }
        output = souffle::ramBitCast(static_cast<souffle::RamSigned>(variant_index));
        return status(SOUFFLE_RS_STATUS_OK);
    }

    std::vector<souffle::RamDomain> fields;
    fields.resize(variant->field_count);
    for (std::size_t index = 0; index < variant->field_count; ++index) {
        int field_status =
            pack_input_schema_value(program, variant->fields[index], row, composite->values[index], fields[index], error);
        if (field_status != status(SOUFFLE_RS_STATUS_OK)) {
            return field_status;
        }
    }

    souffle::RamDomain payload = 0;
    if (variant->field_count == 0) {
        payload = program->program->getRecordTable().pack(fields.data(), fields.size());
    } else if (variant->field_count == 1) {
        payload = fields[0];
    } else {
        payload = program->program->getRecordTable().pack(fields.data(), fields.size());
    }

    souffle::RamDomain record[2] = {
        souffle::ramBitCast(static_cast<souffle::RamSigned>(variant_index)),
        payload
    };
    output = program->program->getRecordTable().pack(record, 2);
    return status(SOUFFLE_RS_STATUS_OK);
}

int pack_input_union_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
) {
    if (schema.child_count == 0 || schema.children == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "union schema has no variants");
    }
    const std::string declared_type = value_declared_type_name(value);
    if (!declared_type.empty() && declared_type != schema_type_name(schema)) {
        for (std::size_t index = 0; index < schema.child_count; ++index) {
            if (schema_declared_type_matches(schema.children[index], declared_type)) {
                return pack_input_schema_value(program, schema.children[index], row, value, output, error);
            }
        }
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input declared type is not a union variant: " + declared_type);
    }
    for (std::size_t index = 0; index < schema.child_count; ++index) {
        if (input_value_matches_schema(schema.children[index], value)) {
            return pack_input_schema_value(program, schema.children[index], row, value, output, error);
        }
    }
    return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value does not match any union variant");
}

int pack_input_schema_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    const SouffleRsRow& row,
    const SouffleRsValue& value,
    souffle::RamDomain& output,
    SouffleRsError* error
) {
    switch (schema.kind) {
    case SchemaTypeKind::Number:
        if (value.kind != SOUFFLE_RS_VALUE_NUMBER) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value kind does not match number schema");
        }
        output = souffle::ramBitCast(static_cast<souffle::RamSigned>(value.as.number));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Unsigned:
        if (value.kind != SOUFFLE_RS_VALUE_UNSIGNED) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value kind does not match unsigned schema");
        }
        output = souffle::ramBitCast(static_cast<souffle::RamUnsigned>(value.as.unsigned_value));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Float:
        if (value.kind != SOUFFLE_RS_VALUE_FLOAT) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value kind does not match float schema");
        }
        output = souffle::ramBitCast(static_cast<souffle::RamFloat>(value.as.float_value));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Symbol:
        if (value.kind != SOUFFLE_RS_VALUE_SYMBOL) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value kind does not match symbol schema");
        }
        output = program->program->getSymbolTable().encode(borrowed_string(value.as.symbol));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Nullary:
        if (value.kind != SOUFFLE_RS_VALUE_NULLARY) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "input value kind does not match nullary schema");
        }
        output = 0;
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Record:
        return pack_input_record_value(program, schema, row, value, output, error);
    case SchemaTypeKind::List:
        return pack_input_list_value(program, schema, row, value, output, error);
    case SchemaTypeKind::Adt:
        return pack_input_adt_value(program, schema, row, value, output, error);
    case SchemaTypeKind::Subtype:
    case SchemaTypeKind::Reference:
    case SchemaTypeKind::Declared:
        if (schema.inner == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "schema wrapper type has no runtime type");
        }
        return pack_input_schema_value(program, *schema.inner, row, value, output, error);
    case SchemaTypeKind::Union:
        return pack_input_union_value(program, schema, row, value, output, error);
    }
    return set_error(error, SOUFFLE_RS_STATUS_ERROR, "unknown schema type kind");
}

SouffleRsCompositeRef push_composite(
    OwnedRelationOutput& owner,
    SouffleRsValueKind kind,
    std::vector<SouffleRsValue> values,
    SouffleRsString variant
) {
    std::size_t index = owner.composites.size();
    owner.composites.push_back(CompositeNode{kind, std::move(values), variant});
    return SouffleRsCompositeRef{index};
}

OwnedRelationOutput* relation_output_owner(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
) {
    if (relation_output == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "relation_output");
        return nullptr;
    }
    if (relation_output->owner == nullptr) {
        set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "relation_output.owner");
        return nullptr;
    }
    return static_cast<OwnedRelationOutput*>(relation_output->owner);
}

int materialize_schema_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
);

int materialize_record_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    if (raw == 0) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "nil record output cannot be decoded as a structured Rust value");
    }
    const souffle::RamDomain* unpacked = program->program->getRecordTable().unpack(raw, schema.child_count);
    if (unpacked == nullptr && schema.child_count != 0) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "record table returned null while unpacking output record");
    }

    std::vector<SouffleRsValue> fields;
    fields.resize(schema.child_count);
    for (std::size_t index = 0; index < schema.child_count; ++index) {
        int field_status =
            materialize_schema_value(program, schema.children[index], unpacked[index], owner, fields[index], error);
        if (field_status != status(SOUFFLE_RS_STATUS_OK)) {
            return field_status;
        }
    }

    output_value.kind = SOUFFLE_RS_VALUE_RECORD;
    output_value.declared_type = null_string();
    output_value.as.composite = push_composite(owner, SOUFFLE_RS_VALUE_RECORD, std::move(fields), null_string());
    return status(SOUFFLE_RS_STATUS_OK);
}

int materialize_list_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    if (schema.child_count != 1 || schema.children == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "list schema must have exactly one element type");
    }

    std::vector<SouffleRsValue> elements;
    std::vector<souffle::RamDomain> seen;
    souffle::RamDomain cursor = raw;
    while (cursor != 0) {
        if (std::find(seen.begin(), seen.end(), cursor) != seen.end()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "cyclic list output cannot be decoded");
        }
        seen.push_back(cursor);

        const souffle::RamDomain* unpacked = program->program->getRecordTable().unpack(cursor, 2);
        if (unpacked == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "record table returned null while unpacking output list");
        }

        SouffleRsValue element{};
        int element_status = materialize_schema_value(program, schema.children[0], unpacked[0], owner, element, error);
        if (element_status != status(SOUFFLE_RS_STATUS_OK)) {
            return element_status;
        }
        elements.push_back(element);
        cursor = unpacked[1];
    }

    output_value.kind = SOUFFLE_RS_VALUE_LIST;
    output_value.declared_type = null_string();
    output_value.as.composite = push_composite(owner, SOUFFLE_RS_VALUE_LIST, std::move(elements), null_string());
    return status(SOUFFLE_RS_STATUS_OK);
}

int materialize_adt_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    if (!schema.adt_is_enum && raw == 0) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "nil ADT output cannot be decoded as a structured Rust value");
    }
    if (schema.adt_variant_count == 0 || schema.adt_variants == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "ADT schema has no variants");
    }
    if (schema.adt_variant_count != 1 && !schema.adt_variants_ordered) {
        return set_error(
            error,
            SOUFFLE_RS_STATUS_ERROR,
            "ordered ADT variant metadata is required before decoding multi-variant ADT output"
        );
    }
    if (schema.adt_is_enum) {
        const auto variant_index = souffle::ramBitCast<souffle::RamSigned>(raw);
        if (variant_index < 0 || static_cast<std::size_t>(variant_index) >= schema.adt_variant_count) {
            return set_error(
                error,
                SOUFFLE_RS_STATUS_ERROR,
                "enum ADT output used variant index outside schema: " + std::to_string(variant_index)
            );
        }

        const SchemaAdtVariant& variant = schema.adt_variants[static_cast<std::size_t>(variant_index)];
        if (variant.field_count != 0) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "enum ADT variant schema unexpectedly has fields");
        }

        output_value.kind = SOUFFLE_RS_VALUE_ADT;
        output_value.declared_type = copy_string(owner, schema_type_name(schema));
        const std::string variant_name = variant.name == nullptr ? std::string() : std::string(variant.name);
        output_value.as.composite =
            push_composite(owner, SOUFFLE_RS_VALUE_ADT, std::vector<SouffleRsValue>{}, copy_string(owner, variant_name));
        return status(SOUFFLE_RS_STATUS_OK);
    }

    const souffle::RamDomain* unpacked = program->program->getRecordTable().unpack(raw, 2);
    if (unpacked == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "record table returned null while unpacking output ADT");
    }

    const auto variant_index = souffle::ramBitCast<souffle::RamSigned>(unpacked[0]);
    if (variant_index < 0 || static_cast<std::size_t>(variant_index) >= schema.adt_variant_count) {
        return set_error(
            error,
            SOUFFLE_RS_STATUS_ERROR,
            "ADT output used variant index outside schema: " + std::to_string(variant_index)
        );
    }

    const SchemaAdtVariant& variant = schema.adt_variants[static_cast<std::size_t>(variant_index)];
    if (variant.field_count != 0 && variant.fields == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "ADT variant schema has fields but no field metadata");
    }

    std::vector<SouffleRsValue> fields;
    fields.resize(variant.field_count);
    if (variant.field_count == 1) {
        int field_status =
            materialize_schema_value(program, variant.fields[0], unpacked[1], owner, fields[0], error);
        if (field_status != status(SOUFFLE_RS_STATUS_OK)) {
            return field_status;
        }
    } else if (variant.field_count > 1) {
        const souffle::RamDomain* payload = program->program->getRecordTable().unpack(unpacked[1], variant.field_count);
        if (payload == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "record table returned null while unpacking output ADT payload");
        }
        for (std::size_t index = 0; index < variant.field_count; ++index) {
            int field_status =
                materialize_schema_value(program, variant.fields[index], payload[index], owner, fields[index], error);
            if (field_status != status(SOUFFLE_RS_STATUS_OK)) {
                return field_status;
            }
        }
    }

    output_value.kind = SOUFFLE_RS_VALUE_ADT;
    output_value.declared_type = copy_string(owner, schema_type_name(schema));
    const std::string variant_name = variant.name == nullptr ? std::string() : std::string(variant.name);
    output_value.as.composite =
        push_composite(owner, SOUFFLE_RS_VALUE_ADT, std::move(fields), copy_string(owner, variant_name));
    return status(SOUFFLE_RS_STATUS_OK);
}

int materialize_union_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    if (schema.child_count == 0 || schema.children == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "union schema has no variants");
    }

    std::string runtime_tag_error;
    char runtime_tag = 0;
    if (!schema_runtime_tag(schema, runtime_tag, runtime_tag_error)) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, runtime_tag_error);
    }

    return materialize_schema_value(program, schema.children[0], raw, owner, output_value, error);
}

int materialize_schema_value(
    SouffleRsProgram* program,
    const SchemaType& schema,
    souffle::RamDomain raw,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    switch (schema.kind) {
    case SchemaTypeKind::Number:
        output_value.kind = SOUFFLE_RS_VALUE_NUMBER;
        output_value.declared_type = null_string();
        output_value.as.number = static_cast<int64_t>(souffle::ramBitCast<souffle::RamSigned>(raw));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Unsigned:
        output_value.kind = SOUFFLE_RS_VALUE_UNSIGNED;
        output_value.declared_type = null_string();
        output_value.as.unsigned_value = static_cast<uint64_t>(souffle::ramBitCast<souffle::RamUnsigned>(raw));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Float:
        output_value.kind = SOUFFLE_RS_VALUE_FLOAT;
        output_value.declared_type = null_string();
        output_value.as.float_value = static_cast<double>(souffle::ramBitCast<souffle::RamFloat>(raw));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Symbol:
        output_value.kind = SOUFFLE_RS_VALUE_SYMBOL;
        output_value.declared_type = null_string();
        output_value.as.symbol = copy_string(owner, program->program->getSymbolTable().decode(raw));
        return status(SOUFFLE_RS_STATUS_OK);
    case SchemaTypeKind::Record:
        return materialize_record_value(program, schema, raw, owner, output_value, error);
    case SchemaTypeKind::List:
        return materialize_list_value(program, schema, raw, owner, output_value, error);
    case SchemaTypeKind::Adt:
        return materialize_adt_value(program, schema, raw, owner, output_value, error);
    case SchemaTypeKind::Subtype:
    case SchemaTypeKind::Reference:
    case SchemaTypeKind::Declared:
        if (schema.inner == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "schema wrapper type has no runtime type");
        }
        {
            int inner_status = materialize_schema_value(program, *schema.inner, raw, owner, output_value, error);
            if (inner_status != status(SOUFFLE_RS_STATUS_OK)) {
                return inner_status;
            }
            output_value.declared_type = copy_string(owner, schema_type_name(schema));
            return status(SOUFFLE_RS_STATUS_OK);
        }
    case SchemaTypeKind::Union:
        return materialize_union_value(program, schema, raw, owner, output_value, error);
    case SchemaTypeKind::Nullary:
        output_value.kind = SOUFFLE_RS_VALUE_NULLARY;
        output_value.declared_type = null_string();
        return status(SOUFFLE_RS_STATUS_OK);
    }
    return set_error(error, SOUFFLE_RS_STATUS_ERROR, "unknown schema type kind");
}

int materialize_value(
    SouffleRsProgram* program,
    souffle::tuple& tuple,
    const souffle::Relation* relation,
    std::size_t column,
    OwnedRelationOutput& owner,
    SouffleRsValue& output_value,
    SouffleRsError* error
) {
    if (const SchemaType* schema = schema_type_for_column(program->name, relation->getName(), column)) {
        if (!schema_matches_attr_tag(*schema, attr_tag(relation, column))) {
            return type_error(error, relation, column, schema_type_name(*schema));
        }
        return materialize_schema_value(program, *schema, tuple[column], owner, output_value, error);
    }

    switch (attr_tag(relation, column)) {
    case 'i': {
        souffle::RamSigned value = 0;
        tuple >> value;
        output_value.kind = SOUFFLE_RS_VALUE_NUMBER;
        output_value.as.number = static_cast<int64_t>(value);
        return status(SOUFFLE_RS_STATUS_OK);
    }
    case 'u': {
        souffle::RamUnsigned value = 0;
        tuple >> value;
        output_value.kind = SOUFFLE_RS_VALUE_UNSIGNED;
        output_value.as.unsigned_value = static_cast<uint64_t>(value);
        return status(SOUFFLE_RS_STATUS_OK);
    }
    case 'f': {
        souffle::RamFloat value = 0.0;
        tuple >> value;
        output_value.kind = SOUFFLE_RS_VALUE_FLOAT;
        output_value.as.float_value = static_cast<double>(value);
        return status(SOUFFLE_RS_STATUS_OK);
    }
    case 's': {
        std::string value;
        tuple >> value;
        output_value.kind = SOUFFLE_RS_VALUE_SYMBOL;
        output_value.as.symbol = copy_string(owner, value);
        return status(SOUFFLE_RS_STATUS_OK);
    }
    case 'r':
    case '+':
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "output composite unpacking requires schema metadata");
    default:
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "unsupported Souffle attribute type");
    }
}

void clear_relation_output(SouffleRsRelationOutput* relation_output) {
    relation_output->relation_name = nullptr;
    relation_output->rows = nullptr;
    relation_output->len = 0;
    relation_output->owner = nullptr;
}

void clear_row_output(SouffleRsRowOutput* row_output) {
    row_output->row = SouffleRsRow{nullptr, nullptr, 0, nullptr, 0};
    row_output->owner = nullptr;
}

int materialize_tuple_row(
    SouffleRsProgram* program,
    const souffle::Relation* relation,
    const souffle::tuple& source_tuple,
    OwnedRelationOutput& owner,
    SouffleRsError* error
) {
    souffle::tuple tuple = source_tuple;
    tuple.rewind();
    SouffleRsRow row{owner.relation_name.c_str(), nullptr, relation->getArity(), nullptr, 0};
    std::unique_ptr<SouffleRsValue[]> values;
    if (relation->getArity() > 0) {
        values = std::make_unique<SouffleRsValue[]>(relation->getArity());
        for (std::size_t column = 0; column < relation->getArity(); ++column) {
            int materialize_status =
                materialize_value(program, tuple, relation, column, owner, values[column], error);
            if (materialize_status != status(SOUFFLE_RS_STATUS_OK)) {
                return materialize_status;
            }
        }
        row.values = values.get();
    }

    owner.row_values.push_back(std::move(values));
    owner.rows.push_back(row);
    return status(SOUFFLE_RS_STATUS_OK);
}

void publish_relation_output(
    std::unique_ptr<OwnedRelationOutput> owner,
    SouffleRsRelationOutput* relation_output
) {
    relation_output->relation_name = owner->relation_name.c_str();
    relation_output->rows = owner->rows.empty() ? nullptr : owner->rows.data();
    relation_output->len = owner->rows.size();
    relation_output->owner = owner.release();
}

void publish_row_output(
    std::unique_ptr<OwnedRelationOutput> owner,
    SouffleRsRowOutput* row_output
) {
    row_output->row = owner->rows.front();
    row_output->owner = owner.release();
}

int materialize_iterator_row(
    SouffleRsRelationIterator* iterator,
    std::uint8_t* has_row_output,
    SouffleRsRowOutput* row_output,
    SouffleRsError* error
) {
    if (iterator == nullptr || iterator->program == nullptr || iterator->relation == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "iterator");
    }
    if (has_row_output == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "has_row_output");
    }
    if (row_output == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "row_output");
    }

    *has_row_output = 0;
    clear_row_output(row_output);
    if (iterator->current == iterator->end) {
        return status(SOUFFLE_RS_STATUS_OK);
    }

    auto owner = std::make_unique<OwnedRelationOutput>();
    owner->relation_name = iterator->relation->getName();
    owner->rows.reserve(1);
    owner->row_values.reserve(1);

    int materialize_status = materialize_tuple_row(
        iterator->program,
        iterator->relation,
        *iterator->current,
        *owner,
        error
    );
    if (materialize_status != status(SOUFFLE_RS_STATUS_OK)) {
        return materialize_status;
    }
    ++iterator->current;

    if (owner->rows.size() != 1) {
        return set_error(error, SOUFFLE_RS_STATUS_ERROR, "iterator returned an invalid row output");
    }

    *has_row_output = 1;
    publish_row_output(std::move(owner), row_output);
    return status(SOUFFLE_RS_STATUS_OK);
}

int materialize_iterator_chunk(
    SouffleRsRelationIterator* iterator,
    std::size_t max_rows,
    std::uint8_t* has_rows_output,
    SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
) {
    if (iterator == nullptr || iterator->program == nullptr || iterator->relation == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "iterator");
    }
    if (has_rows_output == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "has_rows_output");
    }
    if (relation_output == nullptr) {
        return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "relation_output");
    }

    *has_rows_output = 0;
    clear_relation_output(relation_output);
    if (max_rows == 0 || iterator->current == iterator->end) {
        return status(SOUFFLE_RS_STATUS_OK);
    }

    auto owner = std::make_unique<OwnedRelationOutput>();
    owner->relation_name = iterator->relation->getName();
    owner->rows.reserve(max_rows);
    owner->row_values.reserve(max_rows);

    std::size_t emitted = 0;
    while (emitted < max_rows && iterator->current != iterator->end) {
        int materialize_status = materialize_tuple_row(
            iterator->program,
            iterator->relation,
            *iterator->current,
            *owner,
            error
        );
        if (materialize_status != status(SOUFFLE_RS_STATUS_OK)) {
            return materialize_status;
        }
        ++iterator->current;
        ++emitted;
    }

    if (!owner->rows.empty()) {
        *has_rows_output = 1;
        publish_relation_output(std::move(owner), relation_output);
    }
    return status(SOUFFLE_RS_STATUS_OK);
}

} // namespace

extern "C" uint32_t souffle_rs_abi_version(void) {
"#,
    );
    output.push_str(&format!("    return {abi_version}u;\n"));
    output.push_str(
        r#"}

extern "C" int souffle_rs_program_new(
    const char* program_name,
    SouffleRsProgram** program_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (program_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "program_output");
        }
        *program_output = nullptr;
        if (program_name == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "program_name");
        }
        auto* program = create_program_by_name(program_name);
        if (program == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, std::string("program not found: ") + program_name);
        }
        *program_output = new SouffleRsProgram(program_name, program);
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_program_set_threads(
    SouffleRsProgram* program,
    size_t thread_count,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (program == nullptr || program->program == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "program");
        }
        program->program->setNumThreads(thread_count);
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_program_insert_row(
    SouffleRsProgram* program,
    const SouffleRsRow* row,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (row == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "row");
        }
        auto* relation = relation_by_name(program, row->relation_name, error);
        if (relation == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }
        if (row->len != relation->getArity()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "row arity does not match relation arity");
        }
        if (row->len != 0 && row->values == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "row.values");
        }
        if (row->composite_count != 0 && row->composites == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "row.composites");
        }

        souffle::tuple tuple(relation);
        for (std::size_t index = 0; index < row->len; ++index) {
            int append_status = append_value(program, tuple, relation, index, *row, row->values[index], error);
            if (append_status != status(SOUFFLE_RS_STATUS_OK)) {
                return append_status;
            }
        }
        relation->insert(tuple);
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_program_run(
    SouffleRsProgram* program,
    const SouffleRsRunOptions* options,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (program == nullptr || program->program == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "program");
        }
        if (options != nullptr && options->thread_count > 0) {
            program->program->setNumThreads(options->thread_count);
        }
        program->program->run();
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_program_read_relation(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (relation_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "relation_output");
        }
        clear_relation_output(relation_output);

        auto* relation = relation_by_name(program, relation_name, error);
        if (relation == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }

        auto owner = std::make_unique<OwnedRelationOutput>();
        owner->relation_name = relation->getName();
        owner->rows.reserve(relation->size());
        owner->row_values.reserve(relation->size());

        for (auto it = relation->begin(); it != relation->end(); ++it) {
            int materialize_status = materialize_tuple_row(program, relation, *it, *owner, error);
            if (materialize_status != status(SOUFFLE_RS_STATUS_OK)) {
                return materialize_status;
            }
        }

        publish_relation_output(std::move(owner), relation_output);
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_program_open_relation_iterator(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRelationIterator** iterator_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (iterator_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "iterator_output");
        }
        *iterator_output = nullptr;

        auto* relation = relation_by_name(program, relation_name, error);
        if (relation == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }

        *iterator_output = new SouffleRsRelationIterator(program, relation);
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_relation_iterator_next(
    SouffleRsRelationIterator* iterator,
    uint8_t* has_row_output,
    SouffleRsRowOutput* row_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        return materialize_iterator_row(iterator, has_row_output, row_output, error);
    });
}

extern "C" int souffle_rs_relation_iterator_next_chunk(
    SouffleRsRelationIterator* iterator,
    size_t max_rows,
    uint8_t* has_rows_output,
    SouffleRsRelationOutput* relation_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        return materialize_iterator_chunk(iterator, max_rows, has_rows_output, relation_output, error);
    });
}

extern "C" int souffle_rs_program_for_each_row(
    SouffleRsProgram* program,
    const char* relation_name,
    SouffleRsRowCallback callback,
    void* user_data,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (callback == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "callback");
        }

        SouffleRsRelationIterator* iterator = nullptr;
        int open_status = souffle_rs_program_open_relation_iterator(program, relation_name, &iterator, error);
        if (open_status != status(SOUFFLE_RS_STATUS_OK)) {
            return open_status;
        }

        while (true) {
            std::uint8_t has_row = 0;
            SouffleRsRowOutput output{SouffleRsRow{nullptr, nullptr, 0, nullptr, 0}, nullptr};
            int next_status = souffle_rs_relation_iterator_next(iterator, &has_row, &output, error);
            if (next_status != status(SOUFFLE_RS_STATUS_OK)) {
                souffle_rs_relation_iterator_free(iterator);
                return next_status;
            }
            if (has_row == 0) {
                souffle_rs_relation_iterator_free(iterator);
                return status(SOUFFLE_RS_STATUS_OK);
            }
            if (output.owner == nullptr) {
                souffle_rs_row_output_free(&output);
                souffle_rs_relation_iterator_free(iterator);
                return set_error(error, SOUFFLE_RS_STATUS_ERROR, "iterator returned an invalid row output");
            }
            int callback_status = callback(&output.row, user_data);
            souffle_rs_row_output_free(&output);
            if (callback_status != status(SOUFFLE_RS_STATUS_OK)) {
                souffle_rs_relation_iterator_free(iterator);
                return set_error(error, SOUFFLE_RS_STATUS_CALLBACK_FAILED, "row callback returned failure");
            }
        }
    });
}

extern "C" int souffle_rs_relation_output_composite_len(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    size_t* len_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (len_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "len_output");
        }
        auto* owner = relation_output_owner(relation_output, error);
        if (owner == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }
        if (composite.index >= owner->composites.size()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "composite reference is out of bounds");
        }
        *len_output = owner->composites[composite.index].values.size();
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_relation_output_composite_value(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    size_t index,
    SouffleRsValue* value_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (value_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "value_output");
        }
        auto* owner = relation_output_owner(relation_output, error);
        if (owner == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }
        if (composite.index >= owner->composites.size()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "composite reference is out of bounds");
        }
        const CompositeNode& node = owner->composites[composite.index];
        if (index >= node.values.size()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "composite value index is out of bounds");
        }
        *value_output = node.values[index];
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" int souffle_rs_relation_output_adt_variant(
    const SouffleRsRelationOutput* relation_output,
    SouffleRsCompositeRef composite,
    SouffleRsString* variant_output,
    SouffleRsError* error
) {
    return catch_boundary(error, [&]() {
        if (variant_output == nullptr) {
            return set_error(error, SOUFFLE_RS_STATUS_NULL_POINTER, "variant_output");
        }
        auto* owner = relation_output_owner(relation_output, error);
        if (owner == nullptr) {
            return status(error == nullptr ? SOUFFLE_RS_STATUS_ERROR : error->status);
        }
        if (composite.index >= owner->composites.size()) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "composite reference is out of bounds");
        }
        const CompositeNode& node = owner->composites[composite.index];
        if (node.kind != SOUFFLE_RS_VALUE_ADT) {
            return set_error(error, SOUFFLE_RS_STATUS_ERROR, "composite reference is not an ADT");
        }
        *variant_output = node.variant;
        return status(SOUFFLE_RS_STATUS_OK);
    });
}

extern "C" void souffle_rs_program_free(SouffleRsProgram* program) {
    delete program;
}

extern "C" void souffle_rs_relation_iterator_free(SouffleRsRelationIterator* iterator) {
    delete iterator;
}

extern "C" void souffle_rs_row_output_free(SouffleRsRowOutput* row_output) {
    if (row_output == nullptr) {
        return;
    }
    auto* owner = static_cast<OwnedRelationOutput*>(row_output->owner);
    delete owner;
    row_output->row = SouffleRsRow{nullptr, nullptr, 0, nullptr, 0};
    row_output->owner = nullptr;
}

extern "C" void souffle_rs_relation_output_free(SouffleRsRelationOutput* relation_output) {
    if (relation_output == nullptr) {
        return;
    }
    auto* owner = static_cast<OwnedRelationOutput*>(relation_output->owner);
    delete owner;
    relation_output->relation_name = nullptr;
    relation_output->rows = nullptr;
    relation_output->len = 0;
    relation_output->owner = nullptr;
}

extern "C" void souffle_rs_error_free(SouffleRsError* error) {
    if (error == nullptr) {
        return;
    }
    delete[] const_cast<char*>(error->message.data);
    error->status = SOUFFLE_RS_STATUS_OK;
    error->message = null_string();
}
"#,
    );

    output
}

fn cxx_string_literal(value: &str) -> String {
    format!("{value:?}")
}

fn render_schema_metadata(
    metadata: &BuildMetadata,
    schemas: &BTreeMap<String, RelationBundle>,
) -> String {
    let mut renderer = CxxSchemaRenderer::new();
    renderer.render_prelude();

    for program in &metadata.programs {
        let Some(schema) = schemas.get(&program.program) else {
            continue;
        };
        renderer.render_program_relations(&program.program, schema);
    }

    renderer.finish()
}

struct CxxSchemaRenderer {
    output: String,
    next_type_id: usize,
    next_relation_id: usize,
    relation_symbols: Vec<String>,
    named_type_symbols: BTreeMap<String, String>,
}

impl CxxSchemaRenderer {
    fn new() -> Self {
        Self {
            output: String::new(),
            next_type_id: 0,
            next_relation_id: 0,
            relation_symbols: Vec::new(),
            named_type_symbols: BTreeMap::new(),
        }
    }

    fn render_prelude(&mut self) {
        self.output.push_str(
            r#"static const SchemaType SCHEMA_TYPE_NUMBER{SchemaTypeKind::Number, "number", nullptr, 0, nullptr, nullptr, 0, false, false};
static const SchemaType SCHEMA_TYPE_UNSIGNED{SchemaTypeKind::Unsigned, "unsigned", nullptr, 0, nullptr, nullptr, 0, false, false};
static const SchemaType SCHEMA_TYPE_FLOAT{SchemaTypeKind::Float, "float", nullptr, 0, nullptr, nullptr, 0, false, false};
static const SchemaType SCHEMA_TYPE_SYMBOL{SchemaTypeKind::Symbol, "symbol", nullptr, 0, nullptr, nullptr, 0, false, false};
static const SchemaType SCHEMA_TYPE_NULLARY{SchemaTypeKind::Nullary, "nullary", nullptr, 0, nullptr, nullptr, 0, false, false};

"#,
        );
    }

    fn render_program_relations(&mut self, program: &str, schema: &RelationBundle) {
        for relation in schema.iter() {
            let relation_id = self.next_relation_id;
            self.next_relation_id += 1;

            let mut attributes = Vec::new();
            for attribute in relation.attributes() {
                let ty = self.render_type(attribute.declared_type());
                attributes.push((attribute.name().to_owned(), ty));
            }

            let attributes_symbol = format!("SCHEMA_RELATION_{relation_id}_ATTRIBUTES");
            if attributes.is_empty() {
                self.output.push_str(&format!(
                    "static const SchemaAttribute* {attributes_symbol} = nullptr;\n"
                ));
            } else {
                self.output.push_str(&format!(
                    "static const SchemaAttribute {attributes_symbol}[] = {{\n"
                ));
                for (name, ty) in &attributes {
                    self.output
                        .push_str(&format!("    {{{}, &{ty}}},\n", cxx_string_literal(name)));
                }
                self.output.push_str("};\n");
            }

            let relation_symbol = format!("SCHEMA_RELATION_{relation_id}");
            self.output.push_str(&format!(
                "static const SchemaRelation {relation_symbol}{{{}, {}, {attributes_symbol}, {}}};\n\n",
                cxx_string_literal(program),
                cxx_string_literal(relation.name()),
                relation.arity()
            ));
            self.relation_symbols.push(relation_symbol);
        }
    }

    fn render_type(&mut self, ty: &TypeRef) -> String {
        match ty {
            TypeRef::Number => "SCHEMA_TYPE_NUMBER".to_owned(),
            TypeRef::Unsigned => "SCHEMA_TYPE_UNSIGNED".to_owned(),
            TypeRef::Float => "SCHEMA_TYPE_FLOAT".to_owned(),
            TypeRef::Symbol => "SCHEMA_TYPE_SYMBOL".to_owned(),
            TypeRef::Nullary => "SCHEMA_TYPE_NULLARY".to_owned(),
            TypeRef::Record(fields) => self.render_record_type(ty, fields),
            TypeRef::List(element) => {
                let child = self.render_type(element);
                self.render_child_type(SchemaKindName::List, &ty.display_name(), &[child], None)
            }
            TypeRef::Adt { .. } => self.render_adt_type(ty),
            TypeRef::Reference { name, .. } => {
                if let Some(inner) = self.named_type_symbols.get(name).cloned() {
                    self.render_wrapper_type(SchemaKindName::Reference, name, &inner)
                } else {
                    self.render_child_type(SchemaKindName::Reference, name, &[], None)
                }
            }
            TypeRef::Subtype { name, base } => {
                let inner = self.render_type(base);
                self.render_wrapper_type(SchemaKindName::Subtype, name, &inner)
            }
            TypeRef::Declared { name, runtime } => {
                let inner = self.render_type(runtime);
                self.render_wrapper_type(SchemaKindName::Declared, name, &inner)
            }
            TypeRef::Union { name, variants } => {
                let children = variants
                    .iter()
                    .map(|variant| self.render_type(variant))
                    .collect::<Vec<_>>();
                self.render_child_type(SchemaKindName::Union, name, &children, None)
            }
        }
    }

    fn render_record_type(&mut self, ty: &TypeRef, fields: &[TypeRef]) -> String {
        let children = fields
            .iter()
            .map(|field| self.render_type(field))
            .collect::<Vec<_>>();
        self.render_child_type(SchemaKindName::Record, &ty.display_name(), &children, None)
    }

    fn render_wrapper_type(&mut self, kind: SchemaKindName, name: &str, inner: &str) -> String {
        self.render_child_type(kind, name, &[], Some(inner))
    }

    fn render_adt_type(&mut self, ty: &TypeRef) -> String {
        let TypeRef::Adt { name, variants, .. } = ty else {
            unreachable!("render_adt_type only accepts ADT schemas");
        };
        if let Some(symbol) = self.named_type_symbols.get(name) {
            return symbol.clone();
        }

        let type_id = self.next_type_id;
        self.next_type_id += 1;
        let type_symbol = format!("SCHEMA_TYPE_{type_id}");
        self.output
            .push_str(&format!("extern const SchemaType {type_symbol};\n"));
        self.named_type_symbols
            .insert(name.clone(), type_symbol.clone());
        let variants_symbol = format!("SCHEMA_TYPE_{type_id}_ADT_VARIANTS");
        let mut rendered_variants = Vec::new();
        let ordered_variants = ty.ordered_adt_variants();
        let variants_are_ordered = ordered_variants.is_some();
        let fallback_variants;
        let variants_to_render: Vec<(&str, &[TypeRef])> =
            if let Some(ordered_variants) = ordered_variants {
                ordered_variants
            } else {
                fallback_variants = variants
                    .iter()
                    .map(|(variant, fields)| (variant.as_str(), fields.as_slice()))
                    .collect::<Vec<_>>();
                fallback_variants
            };

        for (variant_name, fields) in variants_to_render {
            let variant_index = rendered_variants.len();
            let fields_symbol = format!("SCHEMA_TYPE_{type_id}_ADT_VARIANT_{variant_index}_FIELDS");
            let field_types = fields
                .iter()
                .map(|field| self.render_type(field))
                .collect::<Vec<_>>();
            if field_types.is_empty() {
                self.output.push_str(&format!(
                    "static const SchemaType* {fields_symbol} = nullptr;\n"
                ));
            } else {
                self.output
                    .push_str(&format!("static const SchemaType {fields_symbol}[] = {{\n"));
                for field_type in &field_types {
                    self.output.push_str(&format!("    {field_type},\n"));
                }
                self.output.push_str("};\n");
            }
            rendered_variants.push((variant_name, fields_symbol, field_types.len()));
        }

        if rendered_variants.is_empty() {
            self.output.push_str(&format!(
                "static const SchemaAdtVariant* {variants_symbol} = nullptr;\n"
            ));
        } else {
            self.output.push_str(&format!(
                "static const SchemaAdtVariant {variants_symbol}[] = {{\n"
            ));
            for (variant_name, fields_symbol, field_count) in &rendered_variants {
                self.output.push_str(&format!(
                    "    {{{}, {fields_symbol}, {field_count}}},\n",
                    cxx_string_literal(variant_name)
                ));
            }
            self.output.push_str("};\n");
        }

        self.output.push_str(&format!(
            "const SchemaType {type_symbol}{{SchemaTypeKind::Adt, {}, nullptr, 0, nullptr, {variants_symbol}, {}, {}, {}}};\n",
            cxx_string_literal(name),
            rendered_variants.len(),
            if variants_are_ordered { "true" } else { "false" },
            if ty.is_enum_adt() { "true" } else { "false" }
        ));
        type_symbol
    }

    fn render_child_type(
        &mut self,
        kind: SchemaKindName,
        name: &str,
        children: &[String],
        inner: Option<&str>,
    ) -> String {
        let type_id = self.next_type_id;
        self.next_type_id += 1;
        let type_symbol = format!("SCHEMA_TYPE_{type_id}");
        let children_symbol = format!("SCHEMA_TYPE_{type_id}_CHILDREN");

        if children.is_empty() {
            self.output.push_str(&format!(
                "static const SchemaType* {children_symbol} = nullptr;\n"
            ));
        } else {
            self.output.push_str(&format!(
                "static const SchemaType {children_symbol}[] = {{\n"
            ));
            for child in children {
                self.output.push_str(&format!("    {child},\n"));
            }
            self.output.push_str("};\n");
        }

        let inner_expr = inner
            .map(|inner| format!("&{inner}"))
            .unwrap_or_else(|| "nullptr".to_owned());
        self.output.push_str(&format!(
            "static const SchemaType {type_symbol}{{SchemaTypeKind::{}, {}, {children_symbol}, {}, {inner_expr}, nullptr, 0, false, false}};\n",
            kind.as_cxx(),
            cxx_string_literal(name),
            children.len()
        ));
        type_symbol
    }

    fn finish(mut self) -> String {
        if self.relation_symbols.is_empty() {
            self.output.push_str(
                "static const SchemaRelation GENERATED_SCHEMA_RELATIONS[] = {{nullptr, nullptr, nullptr, 0}};\n\n",
            );
        } else {
            self.output
                .push_str("static const SchemaRelation GENERATED_SCHEMA_RELATIONS[] = {\n");
            for relation in &self.relation_symbols {
                self.output.push_str(&format!("    {relation},\n"));
            }
            self.output.push_str("};\n\n");
        }
        self.output
    }
}

#[derive(Clone, Copy, IntoStaticStr)]
enum SchemaKindName {
    Record,
    List,
    Subtype,
    Union,
    Reference,
    Declared,
}

impl SchemaKindName {
    fn as_cxx(self) -> &'static str {
        self.into()
    }
}
